Repository virtualsatellite/VirtualSatellite4-Core, pull requests merged in 2019-07, with the labels that each got.

#124 Move launch configurations to parent project - (Task #123)
  launchers/EMF Ecore Generator.launch
  launchers/Generate Language Infrastructure (de.dlr.sc.virsat.model.calculation).launch
  launchers/Launch Runtime Eclipse.launch
  launchers/SwtBot Recorder.launch
  launchers/SwtBot Tests.launch
  launchers/VirSat Core Application (SuperUser).launch
  launchers/VirSat Core Application (other).launch
  launchers/VirSat Core Application (user).launch
  launchers/VirSat Core Build Development (Deploy Local).launch
  launchers/VirSat Core Build Development (Deploy Unsecured).launch
  launchers/VirSat Core Build Development AllTests JavaDoc.launch
  launchers/VirSat Core Build Development Surefire.launch
  launchers/VirSat Core Build Development.launch
  launchers/VirSat Core Build Integration.launch
  launchers/VirSat Core Build Release.launch
  launchers/VirSat Core Concept IDE.launch
  launchers/VirSat Core Execute All Tests.launch
  launchers/VirSat Core Update Pom versions.launch
  launchers/VirSat Core Update Target.launch
  launchers/VirSat Core Update Test Resources.launch
  launchers/VirSatCore Build Manual.launch
Labels: build

#128 Improved Virtual Satellite Deployment
  .travis.yml
  bash/deploy_sourceforge.sh
  bash/maven_build.sh
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ProductStructureTest.java
Labels: build, comfort/usability

#130 Added waitForEditor condition for SWTBotTest cases
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ASwtBotTestCase.java
Labels: build

#137 Fixing deployment - (Task #136)
  bash/deploy_sourceforge.sh
  de.dlr.sc.virsat.product/pom.xml
Labels: bug, build

#141 Adding the new manual
  de.dlr.sc.virsat.docs.feature/src/docs/VirSat_Core_User_Manual.adoc
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterExtendedProductStructures/AssemblyTreeInheritedMassesFromStorage.png
Labels: comfort/usability, quality

#142 Feature/task 87 missing resource valid
  de.dlr.sc.virsat.build.test/src/de/dlr/sc/virsat/build/validator/core/DvlmMissingResourcePropertyValidatorTest.java
  de.dlr.sc.virsat.build/src/de/dlr/sc/virsat/build/validator/VirSatValidatorBuilder.java
  de.dlr.sc.virsat.build/src/de/dlr/sc/virsat/build/validator/core/DvlmMissingResourcePropertyValidator.java
  de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyResourceTest.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyFloat.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyResource.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/AUiSnippetGenericPropertyInstances.java
Labels: comfort/usability, quality, ui

#143 Feature/task 77 text on a commit dialo
  de.dlr.sc.virsat.svn.ui/src/de/dlr/sc/virsat/svn/ui/action/CustomCommitAction.java
  de.dlr.sc.virsat.svn.ui/src/de/dlr/sc/virsat/svn/ui/dialog/CommitMessageDialog.java
Labels: comfort/usability, easy

#145 Removed dependency to google guava - (Task #35)
  de.dlr.sc.virsat.model/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model/src/de/dlr/sc/virsat/model/dvlm/concepts/util/ActiveConceptHelper.java
Labels: easy, quality

#144 Added set methods and tested them - (Task #82)
  de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyFloatTest.java
  de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyIntTest.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/ABeanUnitProperty.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyFloat.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyInt.java
Labels: comfort/usability, quality

#147 Implement table keyboard navigation in generic table snippet
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/AUiSnippetGenericTable.java
Labels: comfort/usability, ui

#157 Feature/task 153 add json external lib
  NOTICE.md
  de.dlr.sc.virsat.external.lib.feature/feature.xml
  de.dlr.sc.virsat.external.lib.json-simple/.checkstyle
  de.dlr.sc.virsat.external.lib.json-simple/.classpath
  de.dlr.sc.virsat.external.lib.json-simple/.project
  de.dlr.sc.virsat.external.lib.json-simple/.settings/edu.umd.cs.findbugs.core.prefs
  de.dlr.sc.virsat.external.lib.json-simple/.settings/org.eclipse.core.resources.prefs
  de.dlr.sc.virsat.external.lib.json-simple/.settings/org.eclipse.jdt.core.prefs
  de.dlr.sc.virsat.external.lib.json-simple/.settings/org.eclipse.m2e.core.prefs
  de.dlr.sc.virsat.external.lib.json-simple/.settings/org.eclipse.mylyn.team.ui.prefs
  de.dlr.sc.virsat.external.lib.json-simple/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.external.lib.json-simple/about.html
  de.dlr.sc.virsat.external.lib.json-simple/about_files/AUTHORS.txt
  de.dlr.sc.virsat.external.lib.json-simple/about_files/LICENSE.txt
  de.dlr.sc.virsat.external.lib.json-simple/build.properties
  de.dlr.sc.virsat.external.lib.json-simple/externalLib/json-simple-1.1.1-javadoc.jar
  de.dlr.sc.virsat.external.lib.json-simple/externalLib/json-simple-1.1.1-sources.jar
  de.dlr.sc.virsat.external.lib.json-simple/externalLib/json-simple-1.1.1.jar
  de.dlr.sc.virsat.external.lib.json-simple/externalLib/src/json-simple-tag_release_1_1_1.zip
  de.dlr.sc.virsat.external.lib.json-simple/pom.xml
  de.dlr.sc.virsat.external.lib.json-simple/src/de/dlr/virsat/external/lib/json/simple/Activator.java
  pom.xml
Labels: feature

#169 Feature/task 163 catia export parts
  de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/catia/CatiaExporterTest.java
  de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/test/AllTests.java
  de.dlr.sc.virsat.model.extension.mechanical/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.mechanical/src/de/dlr/sc/virsat/model/extension/mechanical/catia/CatiaExporter.java
  de.dlr.sc.virsat.model.extension.mechanical/src/de/dlr/sc/virsat/model/extension/mechanical/catia/CatiaProperties.java
Labels: feature

#175 Added mechanical concept to overtarget - (Task #166)
  de.dlr.sc.virsat.target/tmodel-src/core_development.tmodel
  de.dlr.sc.virsat.target/tmodel-src/core_integration.tmodel
Labels: feature

#172 Added getAllSuperSeis method for SEIs and beans - (Task #168)
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/structural/ABeanStructuralElementInstance.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/structural/IBeanStructuralElementInstance.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/util/BeanStructuralElementInstanceHelper.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/concept/types/util/BeanStructuralElementInstanceHelperTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/model/TestStructuralElementInstanceTest.java
  de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/dvlm/structural/util/StructuralElementInstanceHelperTest.java
  de.dlr.sc.virsat.model/src/de/dlr/sc/virsat/model/dvlm/structural/util/StructuralElementInstanceHelper.java
Labels: comfort/usability

#177 Added mechanical.test plugin into the test.feature - (Task #176)
  de.dlr.sc.virsat.test.feature/feature.xml
Labels: build

#182 Update the generated files of the mechancial concept - (Task #181)
  de.dlr.sc.virsat.model.extension.mechanical.ui/plugin.xml
  de.dlr.sc.virsat.model.extension.mechanical/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.mechanical/concept/concept_v0_1.xmi
Labels: quality

#179 Added export of Products to Json - (Task #173)
  de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/catia/CatiaExporterTest.java
  de.dlr.sc.virsat.model.extension.mechanical/src/de/dlr/sc/virsat/model/extension/mechanical/catia/CatiaExporter.java
  de.dlr.sc.virsat.model.extension.mechanical/src/de/dlr/sc/virsat/model/extension/mechanical/catia/CatiaProperties.java
Labels: feature

#184 Add Catia helper class - (Task #183)
  de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/catia/util/CatiaHelperTest.java
  de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/test/AllTests.java
  de.dlr.sc.virsat.model.extension.mechanical/src/de/dlr/sc/virsat/model/extension/mechanical/catia/util/CatiaHelper.java
Labels: feature

#186 Feature/task 180 catia export content
  de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/catia/CatiaExporterTest.java
  de.dlr.sc.virsat.model.extension.mechanical/src/de/dlr/sc/virsat/model/extension/mechanical/catia/CatiaExporter.java
  de.dlr.sc.virsat.model/src/de/dlr/sc/virsat/model/dvlm/inheritance/InheritanceCopier.java
Labels: feature

#188 Fixed missing images in maturity chapter in user manual
  bash/maven_build.sh
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/ActivateMaturityParameters.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/AddMaturityConcept.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/MaturityOverview.png
Labels: bug, build, manual

#115 Integrate author verification into build process
  .gitignore
  .mailmap
  .settings/org.eclipse.core.resources.prefs
  .travis.yml
  README.md
  bash/verify_commit_authors.sh
  cla/20190724_DLR_Individual_Contributor_License_Agreement_Virtual_Satellite_en_v1.2.pdf
  cla/20190724_Declaration_of_consent_data_processing_and_privacy_policy_Virtual_Satellite_en_v1.2.pdf
  cla/20190724_Einverständniserklärung_Datenverabreitung_und_Datenschutz_VirtualSatellite_de_v1.2.pdf
  known_authors.txt
Labels: build, feature

#190 Feature/task 178 Implement first mapping of imported JSON to existing model
  de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/catia/CatiaImporterTest.java
  de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/test/AllTests.java
  de.dlr.sc.virsat.model.extension.mechanical/src/de/dlr/sc/virsat/model/extension/mechanical/catia/CatiaImporter.java
  de.dlr.sc.virsat.model.extension.mechanical/src/de/dlr/sc/virsat/model/extension/mechanical/catia/util/CatiaHelper.java
Labels: feature

#189 Feature/task 187 catia export file wri
  de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/catia/CatiaExporterTest.java
  de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/catia/CatiaFileWriterTest.java
  de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/test/AllTests.java
  de.dlr.sc.virsat.model.extension.mechanical/src/de/dlr/sc/virsat/model/extension/mechanical/catia/CatiaExporter.java
  de.dlr.sc.virsat.model.extension.mechanical/src/de/dlr/sc/virsat/model/extension/mechanical/catia/CatiaFileWriter.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/test/AProjectTestCase.java
Labels: feature

#162 Updating Issue Templates
  .github/ISSUE_TEMPLATE/bugreport.md
  .github/ISSUE_TEMPLATE/release.md
Labels: build, easy, release

#193 Feature/task 170 catia import JSON
  de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/catia/CatiaImporterTest.java
  de.dlr.sc.virsat.model.extension.mechanical/src/de/dlr/sc/virsat/model/extension/mechanical/catia/CatiaImporter.java
Labels: feature
