Repository virtualsatellite/VirtualSatellite4-Core, pull requests merged in 2019-12, with the labels that each got.

#384 Improved indentation in generateValidatorTests- (Task #383)
  de.dlr.sc.virsat.model.concept.test/resources/expectedOutputFilesForGenerators/AStructuralElementInstanceValidatorTest.java
  de.dlr.sc.virsat.model.concept/src/de/dlr/sc/virsat/model/concept/generator/tests/GenerateValidatorTests.xtend
  de.dlr.sc.virsat.model.concept/xtend-gen/de/dlr/sc/virsat/model/concept/generator/tests/GenerateValidatorTests.java
Labels: quality

#385 Improved checkstyle definitions - (Task #382)
  checkStylesDefinition.xml
  de.dlr.sc.virsat.model.calculation.ui/src/de/dlr/sc/virsat/model/calculation/ui/contentassist/EquationDSLProposalProvider.xtend
  de.dlr.sc.virsat.model.calculation.ui/src/de/dlr/sc/virsat/model/calculation/ui/labeling/EquationDSLDescriptionLabelProvider.xtend
  de.dlr.sc.virsat.model.calculation.ui/src/de/dlr/sc/virsat/model/calculation/ui/labeling/EquationDSLLabelProvider.xtend
  de.dlr.sc.virsat.model.calculation.ui/src/de/dlr/sc/virsat/model/calculation/ui/outline/EquationDSLOutlineTreeProvider.xtend
  de.dlr.sc.virsat.model.calculation.ui/src/de/dlr/sc/virsat/model/calculation/ui/quickfix/EquationDSLQuickfixProvider.xtend
  de.dlr.sc.virsat.model.calculation.ui/xtend-gen/de/dlr/sc/virsat/model/calculation/ui/contentassist/EquationDSLProposalProvider.java
  de.dlr.sc.virsat.model.calculation.ui/xtend-gen/de/dlr/sc/virsat/model/calculation/ui/labeling/EquationDSLDescriptionLabelProvider.java
  de.dlr.sc.virsat.model.calculation.ui/xtend-gen/de/dlr/sc/virsat/model/calculation/ui/labeling/EquationDSLLabelProvider.java
  de.dlr.sc.virsat.model.calculation.ui/xtend-gen/de/dlr/sc/virsat/model/calculation/ui/outline/EquationDSLOutlineTreeProvider.java
  de.dlr.sc.virsat.model.calculation.ui/xtend-gen/de/dlr/sc/virsat/model/calculation/ui/quickfix/EquationDSLQuickfixProvider.java
  de.dlr.sc.virsat.model.calculation/src/de/dlr/sc/virsat/model/calculation/formatting/EquationDSLFormatter.xtend
  de.dlr.sc.virsat.model.calculation/src/de/dlr/sc/virsat/model/calculation/generator/EquationDSLGenerator.xtend
  de.dlr.sc.virsat.model.calculation/src/de/dlr/sc/virsat/model/calculation/scoping/EquationDSLScopeProvider.xtend
  de.dlr.sc.virsat.model.calculation/src/de/dlr/sc/virsat/model/calculation/scoping/EquationSectionImportedNamespaceAwareLocalScopeProvider.xtend
  de.dlr.sc.virsat.model.calculation/src/de/dlr/sc/virsat/model/calculation/scoping/EquationSectionNamesProvider.xtend
  de.dlr.sc.virsat.model.calculation/src/de/dlr/sc/virsat/model/calculation/validation/EquationDSLValidator.xtend
  de.dlr.sc.virsat.model.calculation/xtend-gen/de/dlr/sc/virsat/model/calculation/formatting/EquationDSLFormatter.java
  de.dlr.sc.virsat.model.calculation/xtend-gen/de/dlr/sc/virsat/model/calculation/generator/EquationDSLGenerator.java
  de.dlr.sc.virsat.model.calculation/xtend-gen/de/dlr/sc/virsat/model/calculation/scoping/EquationSectionImportedNamespaceAwareLocalScopeProvider.java
  de.dlr.sc.virsat.model.calculation/xtend-gen/de/dlr/sc/virsat/model/calculation/validation/EquationDSLValidator.java
  de.dlr.sc.virsat.model.concept.test/src/de/dlr/sc/virsat/model/concept/ConceptLanguageTest.xtend
  de.dlr.sc.virsat.model.concept.test/xtend-gen/de/dlr/sc/virsat/model/concept/ConceptLanguageTest.java
  de.dlr.sc.virsat.model.concept.ui/src/de/dlr/sc/virsat/model/concept/ui/contentassist/ConceptLanguageProposalProvider.xtend
  de.dlr.sc.virsat.model.concept.ui/src/de/dlr/sc/virsat/model/concept/ui/labeling/ConceptLanguageDescriptionLabelProvider.xtend
  de.dlr.sc.virsat.model.concept.ui/src/de/dlr/sc/virsat/model/concept/ui/labeling/ConceptLanguageLabelProvider.xtend
  de.dlr.sc.virsat.model.concept.ui/src/de/dlr/sc/virsat/model/concept/ui/outline/ConceptLanguageOutlineTreeProvider.xtend
  de.dlr.sc.virsat.model.concept.ui/src/de/dlr/sc/virsat/model/concept/ui/quickfix/ConceptLanguageQuickfixProvider.xtend
  de.dlr.sc.virsat.model.concept.ui/xtend-gen/de/dlr/sc/virsat/model/concept/ui/contentassist/ConceptLanguageProposalProvider.java
  de.dlr.sc.virsat.model.concept.ui/xtend-gen/de/dlr/sc/virsat/model/concept/ui/labeling/ConceptLanguageDescriptionLabelProvider.java
  de.dlr.sc.virsat.model.concept.ui/xtend-gen/de/dlr/sc/virsat/model/concept/ui/labeling/ConceptLanguageLabelProvider.java
  de.dlr.sc.virsat.model.concept.ui/xtend-gen/de/dlr/sc/virsat/model/concept/ui/outline/ConceptLanguageOutlineTreeProvider.java
  de.dlr.sc.virsat.model.concept.ui/xtend-gen/de/dlr/sc/virsat/model/concept/ui/quickfix/ConceptLanguageQuickfixProvider.java
  de.dlr.sc.virsat.model.concept/src/de/dlr/sc/virsat/model/concept/builder/resources/ResourceAccessBuilder.xtend
  de.dlr.sc.virsat.model.concept/src/de/dlr/sc/virsat/model/concept/generator/IGeneratorGapGenerator.xtend
  de.dlr.sc.virsat.model.concept/src/de/dlr/sc/virsat/model/concept/generator/commands/GenerateArrayCreateAddCommand.xtend
  de.dlr.sc.virsat.model.concept/src/de/dlr/sc/virsat/model/concept/generator/commands/GenerateCategoryCreateAddCommand.xtend
  de.dlr.sc.virsat.model.concept/xtend-gen/de/dlr/sc/virsat/model/concept/builder/resources/ResourceAccessBuilder.java
  de.dlr.sc.virsat.model.concept/xtend-gen/de/dlr/sc/virsat/model/concept/generator/IGeneratorGapGenerator.java
  de.dlr.sc.virsat.model.concept/xtend-gen/de/dlr/sc/virsat/model/concept/generator/commands/GenerateArrayCreateAddCommand.java
  de.dlr.sc.virsat.model.concept/xtend-gen/de/dlr/sc/virsat/model/concept/generator/commands/GenerateCategoryCreateAddCommand.java
Labels: quality

#368 Feature/task 223 improve naming concept selection
  de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/dvlm/concepts/registry/ActiveConceptConfigurationElementTest.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/dvlm/concepts/registry/ActiveConceptConfigurationElement.java
  de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/dvlm/concepts/util/ActiveConceptHelperTest.java
  de.dlr.sc.virsat.model.ui/src/de/dlr/sc/virsat/model/ui/provider/ActiveConceptsLabelProvider.java
  de.dlr.sc.virsat.model/src/de/dlr/sc/virsat/model/dvlm/concepts/util/ActiveConceptHelper.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/general/UiSnippetActiveConcepts.java
Labels: easy, ui

#398 Added functionality to improve log on svn operations - (Task #391)
  de.dlr.sc.virsat.svn.ui/src/de/dlr/sc/virsat/svn/ui/action/CustomCommitAction.java
  de.dlr.sc.virsat.svn.ui/src/de/dlr/sc/virsat/svn/ui/action/CustomUpdateAction.java
  de.dlr.sc.virsat.svn.ui/src/de/dlr/sc/virsat/svn/ui/decoration/VirSatSvnRevisionStatusUtil.java
Labels: bug, comfort/usability

#401 Only show concept section in palette if there are non-abstract types in it - (Task #400)
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uieingine/ui/palette/ConceptPaletteView.java
Labels: ui

#405 Downstreaming server feature - (Task #404)
  de.dlr.sc.virsat.p2updatesite/category.xml
  de.dlr.sc.virsat.target/tmodel-src/core_development.tmodel
  de.dlr.sc.virsat.target/tmodel-src/core_integration.tmodel
Labels: build

#395 Improved logging for null objects in resource - (Task #394)
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/resources/VirSatResourceSetTest.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/resources/VirSatResourceSet.java
Labels: bug, comfort/usability

#403 Error reporting in equation builder on errors in resources - (Task #392)
  de.dlr.sc.virsat.model.calculation.tests/src/de/dlr/sc/virsat/model/calculation/compute/IncrementalEquationBuilderTest.java
  de.dlr.sc.virsat.model.calculation/src/de/dlr/sc/virsat/model/calculation/compute/IncrementalEquationBuilder.java
Labels: comfort/usability
