Repository virtualsatellite/VirtualSatellite4-Core, pull requests merged in 2019-11, with the labels that each got.

#319 Added Try Catch to avoid NPE when executing on linux
  de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/Activator.java
  de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/vtkClient/VtkClientVisUpdateHandler.java
Labels: bug, comfort/usability, quality

#321 Feature/task 97 enable and disable val
  de.dlr.sc.virsat.build/src/de/dlr/sc/virsat/build/validator/RepoValidatorsInstantiator.java
  de.dlr.sc.virsat.build/src/de/dlr/sc/virsat/build/validator/VirSatValidatorBuilder.java
  de.dlr.sc.virsat.build/src/de/dlr/sc/virsat/build/validator/core/DvlmNamingConventionValidator.java
  de.dlr.sc.virsat.model.edit/plugin.properties
  de.dlr.sc.virsat.model.edit/src-gen/de/dlr/sc/virsat/model/dvlm/provider/RepositoryItemProvider.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/build/validator/core/RepoValidatorsInstantiatorTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/test/AllTests.java
  de.dlr.sc.virsat.model/model/dvlm.ecore
  de.dlr.sc.virsat.model/model/dvlm.genmodel
  de.dlr.sc.virsat.model/model/dvlm.history
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/DVLMPackage.java
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/Repository.java
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/categories/ATypeInstance.java
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/categories/Category.java
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/categories/propertyinstances/ResourcePropertyInstance.java
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/categories/propertyinstances/UnitValuePropertyInstance.java
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/concepts/Concept.java
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/general/IAssignedDiscipline.java
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/general/IInstance.java
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/impl/DVLMPackageImpl.java
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/impl/RepositoryImpl.java
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/structural/StructuralElementInstance.java
  de.dlr.sc.virsat.uiengine.ui/plugin.xml
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/general/UiSnippetSuppressedValidators.java
Labels: feature

#348 Fixed exception for first git commit - (Task #347)
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/action/git/GitCommitAction.java
Labels: bug

#346 Removed excel menu registration and handlers - (Task #344)
  de.dlr.sc.virsat.excel.ui/plugin.xml
  de.dlr.sc.virsat.excel.ui/src/de/dlr/sc/virsat/excel/ui/handler/ExportHandler.java
  de.dlr.sc.virsat.excel.ui/src/de/dlr/sc/virsat/excel/ui/handler/ImportHandler.java
Labels: bug

#345 Fixed calculation bug introduced during an earlier refactoring - (Task #343)
  de.dlr.sc.virsat.model.calculation.test/src/de/dlr/sc/virsat/model/calculation/compute/ExpressionHelperTest.java
  de.dlr.sc.virsat.model.calculation/src/de/dlr/sc/virsat/model/calculation/compute/ExpressionHelper.java
Labels: bug

#349 Added refresh after a git update action - (Task #341)
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/action/git/GitUpdateAction.java
Labels: bug

#358 Updated Checkstyle setting and version - (Task #357)
  checkStylesDefinition.xml
  maven/pom.xml
Labels: bug, build

#353 Resolve potential proxies in DMFSaveCommand- (Task #351)
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/resources/dmf/DmfResourceSaveCommandTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/test/AllTests.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/resources/dmf/DmfResourceSaveCommand.java
Labels: bug

#369 Updated build.xml with more precise exclusion statements - (Task #367)
  build.xml
Labels: build, quality

#360 Tag views of beta concept as beta - (Task #323)
  de.dlr.sc.virsat.model.extension.mechanical.ui/src/de/dlr/sc/virsat/model/extension/mechanical/ui/wizards/CadExportPage.java
  de.dlr.sc.virsat.model.extension.mechanical.ui/src/de/dlr/sc/virsat/model/extension/mechanical/ui/wizards/CadExportWizard.java
  de.dlr.sc.virsat.model.extension.mechanical.ui/src/de/dlr/sc/virsat/model/extension/mechanical/ui/wizards/CadImportPage.java
  de.dlr.sc.virsat.model.extension.mechanical.ui/src/de/dlr/sc/virsat/model/extension/mechanical/ui/wizards/CadImportWizard.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/wizard/ConstraintTablePage.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/wizard/ConstraintTableWizard.java
Labels: ui

#350 Created generator class for validator tests
  de.dlr.sc.virsat.model.concept.test/resources/expectedOutputFilesForGenerators/AStructuralElementInstanceValidatorTest.java
  de.dlr.sc.virsat.model.concept.test/resources/expectedOutputFilesForGenerators/AllTestsGen.java
  de.dlr.sc.virsat.model.concept.test/resources/expectedOutputFilesForGenerators/StructuralElementInstanceValidatorTest.java
  de.dlr.sc.virsat.model.concept.test/src/de/dlr/sc/virsat/model/concept/generator/tests/GenerateValidatorTestsTest.xtend
  de.dlr.sc.virsat.model.concept.test/src/de/dlr/sc/virsat/model/concept/test/AllTests.java
  de.dlr.sc.virsat.model.concept.test/xtend-gen/de/dlr/sc/virsat/model/concept/generator/tests/GenerateValidatorTestsTest.java
  de.dlr.sc.virsat.model.concept/src/de/dlr/sc/virsat/model/concept/generator/ConceptLanguageGenerator.xtend
  de.dlr.sc.virsat.model.concept/src/de/dlr/sc/virsat/model/concept/generator/tests/GenerateAllTests.xtend
  de.dlr.sc.virsat.model.concept/src/de/dlr/sc/virsat/model/concept/generator/tests/GenerateValidatorTests.xtend
  de.dlr.sc.virsat.model.concept/xtend-gen/de/dlr/sc/virsat/model/concept/generator/ConceptLanguageGenerator.java
  de.dlr.sc.virsat.model.concept/xtend-gen/de/dlr/sc/virsat/model/concept/generator/tests/GenerateAllTests.java
  de.dlr.sc.virsat.model.concept/xtend-gen/de/dlr/sc/virsat/model/concept/generator/tests/GenerateValidatorTests.java
Labels: concept IDE

#284 Improved SWTBot test cases
  de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/dvlm/qudv/util/QudvUnitHelperTest.java
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/saveablesprovider/VirSatProjectSaveablesProvider.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ASwtBotTestCase.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/CalculationTest.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/InheritanceTest.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ProjectUiAllTests.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/util/VirSatWaitForProjectBuilder.java
Labels: bug, build, quality

#371 Updated categories of VirSat Importers/Exporters - Task (#324)
  de.dlr.sc.virsat.excel.ui/plugin.xml
  de.dlr.sc.virsat.model.extension.funcelectrical.ui/plugin.xml
Labels: ui

#375 Replaced about.html in team.ui plugin with default about.html - (Task #335)
  de.dlr.sc.virsat.team.ui/about.html
Labels: quality

#377 Using the Excel Import Wizard always gives a NPE - Task #329
  de.dlr.sc.virsat.excel.ui/src/de/dlr/sc/virsat/excel/ui/wizards/ImportWizard.java
  de.dlr.sc.virsat.model.extension.funcelectrical.test/resources/ImportElementDefinitionTest.xlsx
  de.dlr.sc.virsat.model.extension.funcelectrical.test/src/de/dlr/sc/virsat/model/extension/funcelectrical/excelExport/FuncElecExporterTest.java
  de.dlr.sc.virsat.model.extension.funcelectrical.test/src/de/dlr/sc/virsat/model/extension/funcelectrical/excelImport/FuncElecImporterTest.java
  de.dlr.sc.virsat.model.extension.funcelectrical.test/src/de/dlr/sc/virsat/model/extension/funcelectrical/excelImport/ImportValidatorTest.java
  de.dlr.sc.virsat.model.extension.funcelectrical.test/src/de/dlr/sc/virsat/model/extension/funcelectrical/test/AllTests.java
  de.dlr.sc.virsat.model.extension.funcelectrical.test/src/de/dlr/sc/virsat/model/extension/funcelectrical/test/ExcelTestCase.java
  de.dlr.sc.virsat.model.extension.funcelectrical/src/de/dlr/sc/virsat/model/extension/funcelectrical/excelImport/FuncElecImporter.java
  de.dlr.sc.virsat.model.extension.funcelectrical/src/de/dlr/sc/virsat/model/extension/funcelectrical/excelImport/ImportValidator.java
Labels: bug
