Repository virtualsatellite/VirtualSatellite4-Core, pull requests merged in 2019-06, with the labels that each got.

#37 Feature/task 32 fix copyright in resou
  de.dlr.sc.virsat.model.concept.test/resources/ManifestMF.java
  de.dlr.sc.virsat.model.concept.test/resources/PluginXml.java
  de.dlr.sc.virsat.model.concept/src/de/dlr/sc/virsat/model/concept/builder/resources/ResourceAccessBuilder.xtend
  de.dlr.sc.virsat.model.concept/xtend-gen/de/dlr/sc/virsat/model/concept/builder/resources/ResourceAccessBuilder.java
Labels: bug, concept IDE, easy

#50 Added trusty flag - (Task #48)
  .travis.yml
Labels: build

#52 Feature/task 41 exception if vtk view
  de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/VtkClientView.java
Labels: bug

#51 Feature/task 49 npe in visualisation c
  de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/snippet/UiSnippetSectionVisualisation.java
Labels: bug

#45 Using history free command execution - (Task #38)
  de.dlr.sc.virsat.model.extension.visualisation/src/de/dlr/sc/virsat/model/extension/visualisation/shape/ShapeEditObserver.java
Labels: bug

#57 Feature/task 56 npe when opening any o
  de.dlr.sc.virsat.model.extension.visualisation.ui/resources/icons/VirSat64.gif
Labels: bug

#54 Feature/task 43 bounding box does not update
  de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/vtkClient/VtkClientVisUpdateHandler.java
  de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/vtkClient/VtkTreeManager.java
Labels: bug

#59 Added support for selecting Qudv Property in vis comparison - (Task #58)
  de.dlr.sc.virsat.model.extension.visualisation.test/src/de/dlr/sc/virsat/model/extension/visualisation/comparison/CompareModelPropertyTest.java
  de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/dialogs/CompareModelPropertyDialog.java
  de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/handler/CompareModelPropertyHandler.java
  de.dlr.sc.virsat.model.extension.visualisation/src/de/dlr/sc/virsat/model/extension/visualisation/comparison/CompareModelProperty.java
Labels: feature

#67 Removed incorrect line - (Task #60)
  de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/vtkClient/VtkClientVisUpdateHandler.java
  de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/vtkClient/VtkTreeManager.java
Labels: bug

#68 Setting debug client before creation of listener threads - (Task #55)
  de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/DebugClientView.java
Labels: bug

#70 Feature/task 69 refactor viewer class
  de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/VtkClientView.java
Labels: quality

#72 Feature/task 44 show bottom panel only if necessary
  de.dlr.sc.virsat.model.extension.visualisation.ui/resources/images/diagram_initial.png
  de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/VtkClientView.java
Labels: bug, comfort/usability

#71 Feature/task 64 change logic of animat
  de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/VtkClientView.java
  de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/vtkClient/VtkClientVisUpdateHandler.java
Labels: feature

#75 Feature/task 66 3 d viewer window only
  de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/VtkClientView.java
Labels: comfort/usability

#105 Removed plugin.properties in build.ui - (Task #81)
  de.dlr.sc.virsat.build.ui/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.build.ui/build.properties
  de.dlr.sc.virsat.build.ui/plugin.properties
Labels: quality

#106 Feature/task 88 UUID field selectedable
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/general/UiSnippetIUuid.java
Labels: comfort/usability, ui

#109 Feature/task 76 have clear indication of super user
  de.dlr.sc.virsat.branding.ui/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.branding.ui/build.properties
  de.dlr.sc.virsat.branding.ui/css/theme-super-user.css
  de.dlr.sc.virsat.branding.ui/plugin.xml
  de.dlr.sc.virsat.model.ui/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.ui/src/de/dlr/sc/virsat/model/ui/Activator.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/general/UiSnippetRoleManagement.java
Labels: comfort/usability, ui

#112 Providing development process for Virtual Satellite Manual
  .gitignore
  README.md
  de.dlr.sc.virsat.branding.ui/resources/images/WelcomeScreen/BIROS_block.jpg
  de.dlr.sc.virsat.branding.ui/resources/images/WelcomeScreen/VirtualSatellite_Modelling_4k.jpg
  de.dlr.sc.virsat.branding.ui/src/de/dlr/sc/virsat/branding/ui/intro/IntroPart.java
  de.dlr.sc.virsat.docs.feature/pom.xml
  de.dlr.sc.virsat.docs.feature/src/docs/VirSat_Core_User_Manual.adoc
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterInstallation/DownloadGitHubRelease.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterInstallation/Execute.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterInstallation/UnZip.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterInstallation/VirtualSatelliteStarted.png
  de.dlr.sc.virsat.model.concept/xtend-gen/de/dlr/sc/virsat/model/concept/builder/resources/ResourceAccessBuilder.java
  maven/pom.xml
Labels: comfort/usability, quality

#113 Added Chapter 1 "Frst Steps"
  de.dlr.sc.virsat.docs.feature/pom.xml
  de.dlr.sc.virsat.docs.feature/src/docs/VirSat_Core_User_Manual.adoc
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterFirstSteps/AddMaturity.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterFirstSteps/AddedElementDefinition.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterFirstSteps/BtnCorePerspective.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterFirstSteps/BtnOpenProject.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterFirstSteps/ChooseWorkspace.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterFirstSteps/ConceptDialog.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterFirstSteps/CreateProductTree.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterFirstSteps/EditorMaturity.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterFirstSteps/Execute.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterFirstSteps/NewprojectDialog.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterFirstSteps/OpenRepository.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterFirstSteps/Perspective.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterFirstSteps/ProductTreeDomain.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterFirstSteps/ProductTreeDomainEditor.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterFirstSteps/RepositoryEditor.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterFirstSteps/SplashAndOSGI.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterFirstSteps/VirtualSatelliteStarted.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/title/VirtualSatellite_Modelling_4k.jpg
  de.dlr.sc.virsat.docs.feature/src/theme/custom-theme.yml
  de.dlr.sc.virsat.product/launch/VirSatCore Build Manual.launch
  maven/pom.xml
Labels: quality

#119 Add null-checks for editor site - (Task #117)
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/AUiSnippetGenericTable.java
Labels: ui
