Repository virtualsatellite/VirtualSatellite4-Core, pull requests merged in 2019-10, with the labels that each got.

#292 Included doc profile in the maven configurations - (Task #291)
  launchers/VirSat Core Build Development (Deploy Local).launch
  launchers/VirSat Core Build Development (Deploy Unsecured).launch
  pom.xml
Labels: build

#298 Feature/task 296 improve user manual
  de.dlr.sc.virsat.docs.feature/src/docs/VirSat_Core_User_Manual.adoc
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/ApplyDiscipline.png
Labels: manual

#302 Feature/task 297 rename catia to cad
  de.dlr.sc.virsat.javadoc.api/help/api_docs.xml
  de.dlr.sc.virsat.model.extension.mechanical.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/cad/CadExporterTest.java
  de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/cad/CadFileHandlerTest.java
  de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/cad/CadImporterTest.java
  de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/cad/command/CopyResourceCommandTest.java
  de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/cad/util/CadHelperTest.java
  de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/test/AllTests.java
  de.dlr.sc.virsat.model.extension.mechanical.ui/plugin.xml
  de.dlr.sc.virsat.model.extension.mechanical.ui/src/de/dlr/sc/virsat/model/extension/mechanical/ui/wizards/ACadImportExportPage.java
  de.dlr.sc.virsat.model.extension.mechanical.ui/src/de/dlr/sc/virsat/model/extension/mechanical/ui/wizards/CadExportPage.java
  de.dlr.sc.virsat.model.extension.mechanical.ui/src/de/dlr/sc/virsat/model/extension/mechanical/ui/wizards/CadExportWizard.java
  de.dlr.sc.virsat.model.extension.mechanical.ui/src/de/dlr/sc/virsat/model/extension/mechanical/ui/wizards/CadImportPage.java
  de.dlr.sc.virsat.model.extension.mechanical.ui/src/de/dlr/sc/virsat/model/extension/mechanical/ui/wizards/CadImportWizard.java
  de.dlr.sc.virsat.model.extension.mechanical/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.mechanical/src/de/dlr/sc/virsat/model/extension/mechanical/cad/CadExporter.java
  de.dlr.sc.virsat.model.extension.mechanical/src/de/dlr/sc/virsat/model/extension/mechanical/cad/CadFileHandler.java
  de.dlr.sc.virsat.model.extension.mechanical/src/de/dlr/sc/virsat/model/extension/mechanical/cad/CadImporter.java
  de.dlr.sc.virsat.model.extension.mechanical/src/de/dlr/sc/virsat/model/extension/mechanical/cad/CadProperties.java
  de.dlr.sc.virsat.model.extension.mechanical/src/de/dlr/sc/virsat/model/extension/mechanical/cad/command/CopyResourceCommand.java
  de.dlr.sc.virsat.model.extension.mechanical/src/de/dlr/sc/virsat/model/extension/mechanical/cad/util/CadHelper.java
Labels: ui

#303 Add subsection for CAD ex- and import - (Task #152)
  de.dlr.sc.virsat.docs.feature/src/docs/VirSat_Core_User_Manual.adoc
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionCAD/export/00_example_tree.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionCAD/export/01_Export.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionCAD/export/02_Export_Wizard.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionCAD/export/03_tree_and_destination_selection.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionCAD/export/04_output.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionCAD/import/00_changed_output.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionCAD/import/01_Import.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionCAD/import/02_Cad_Import_Wizard.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionCAD/import/03_tree_and_destination_selection.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionCAD/import/04_model_changes.PNG
Labels: comfort/usability, manual

#304 Don't send unnecessary notifications to editor listener - (Task #299)
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/editingDomain/VirSatTransactionalEditingDomain.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/markers/VirSatProblemMarkerHelper.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/resources/VirSatResourceSet.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/resources/VirSatResourceSetUtil.java
Labels: bug

#310 Fixed minor issue with Author Verification
  .mailmap
  bash/verify_commit_authors.sh
  known_authors.txt
Labels: bug, build

#311 Update Project Set - (Task #308)
  projectSet/projectSet.psf
Labels: easy

#314 Added test case for inheritance with no common ancestors - (Task #140)
  de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/dvlm/inheritance/InheritanceCopierTest.java
Labels: quality

#317 Add generated DMF resources in extension.tests - (Task #307)
  de.dlr.sc.virsat.model.extension.tests/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/EnumTestEnum.java
  de.dlr.sc.virsat.model.extension.tests/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/impl/TestCategoryAllPropertyImpl.java
  de.dlr.sc.virsat.model.extension.tests/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/impl/TestCategoryBaseImpl.java
  de.dlr.sc.virsat.model.extension.tests/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/impl/TestCategoryCompositionArrayImpl.java
  de.dlr.sc.virsat.model.extension.tests/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/impl/TestCategoryCompositionImpl.java
  de.dlr.sc.virsat.model.extension.tests/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/impl/TestCategoryExtendsImpl.java
  de.dlr.sc.virsat.model.extension.tests/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/impl/TestCategoryIntrinsicArrayImpl.java
  de.dlr.sc.virsat.model.extension.tests/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/impl/TestCategoryReferenceArrayImpl.java
  de.dlr.sc.virsat.model.extension.tests/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/impl/TestCategoryReferenceImpl.java
  de.dlr.sc.virsat.model.extension.tests/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/impl/TestMassParametersImpl.java
  de.dlr.sc.virsat.model.extension.tests/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/impl/TestParameterImpl.java
  de.dlr.sc.virsat.model.extension.tests/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/impl/TestsFactoryImpl.java
  de.dlr.sc.virsat.model.extension.tests/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/impl/TestsPackageImpl.java
Labels: build

#295 Feature/task 293 vir sat add ide setup
  de.dlr.sc.virsat.docs.feature/src/docs/VirSat_Core_Developer_Manual.adoc
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterIdeInstallation/subsectionGitIdeSetup/10_OpenVirsatTarget.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterIdeInstallation/subsectionGitIdeSetup/11_ImportProject.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterIdeInstallation/subsectionGitIdeSetup/12_ImportProjectsGit.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterIdeInstallation/subsectionGitIdeSetup/13_LocalRepository.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterIdeInstallation/subsectionGitIdeSetup/14_SelectVirtualSatelliteCore.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterIdeInstallation/subsectionGitIdeSetup/15_ImportEclipse.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterIdeInstallation/subsectionGitIdeSetup/16_ImportAll.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterIdeInstallation/subsectionGitIdeSetup/17_done.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterIdeInstallation/subsectionGitIdeSetup/1_MainView.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterIdeInstallation/subsectionGitIdeSetup/2_OpenPerspective.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterIdeInstallation/subsectionGitIdeSetup/3_OpenPerspedctiveGit.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterIdeInstallation/subsectionGitIdeSetup/4.1_CloneGitUrl.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterIdeInstallation/subsectionGitIdeSetup/4_CloneUrl.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterIdeInstallation/subsectionGitIdeSetup/5_InsertGitUrl.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterIdeInstallation/subsectionGitIdeSetup/6_BranchSelection.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterIdeInstallation/subsectionGitIdeSetup/7_LocalDestination.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterIdeInstallation/subsectionGitIdeSetup/8_CheckoutBranch.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterIdeInstallation/subsectionGitIdeSetup/9_SelectWorkingTree.PNG
Labels: manual

#316 Feature/task 313 don't run validators from inactive concepts
  de.dlr.sc.virsat.build/src/de/dlr/sc/virsat/build/validator/VirSatValidatorBuilder.java
Labels: bug
