Repository virtualsatellite/VirtualSatellite4-Core, pull requests merged in 2019-08, with the labels that each got.

#197 Feature/task 196 fix table viewer navigation
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/AUiSnippetGenericTable.java
Labels: bug

#200 Bug fix in verify_commit_authors.sh
  bash/verify_commit_authors.sh
Labels: bug, build

#208 Feature/task 206 create a generic bean traverser
  .mailmap
  checkStylesDefinition.xml
  de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/edit/test/AllTests.java
  de.dlr.sc.virsat.model.edit/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/structural/tree/BeanStructuralTreeTraverser.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/structural/tree/IBeanStructuralTreeTraverserMatcher.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/concept/types/structural/tree/BeanStructuralTreeTraverserTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/concept/types/structural/tree/MockMatcher.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/test/AllTests.java
Labels: comfort/usability

#212 Feature/task 211 travis build fails du
  de.dlr.sc.virsat.target/tmodel-src/virsat.tmodel
  de.dlr.sc.virsat.target/virsat.target
Labels: bug, build

#217 Feature/task 213 npe opening unit mana
  de.dlr.sc.virsat.qudv.ui/src/de/dlr/sc/virsat/qudv/ui/editor/snippets/UiSnippetQuantityKindManagement.java
Labels: bug

#207 Add warning for elements of beta concepts - (Task #205)
  de.dlr.sc.virsat.external.lib.commons.cli/plugin.xml
  de.dlr.sc.virsat.model.concept.ide/src-gen/de/dlr/sc/virsat/model/concept/ide/contentassist/antlr/ConceptLanguageParser.java
  de.dlr.sc.virsat.model.concept.ide/src-gen/de/dlr/sc/virsat/model/concept/ide/contentassist/antlr/internal/InternalConceptLanguage.g
  de.dlr.sc.virsat.model.concept.ide/src-gen/de/dlr/sc/virsat/model/concept/ide/contentassist/antlr/internal/InternalConceptLanguage.tokens
  de.dlr.sc.virsat.model.concept.ide/src-gen/de/dlr/sc/virsat/model/concept/ide/contentassist/antlr/internal/InternalConceptLanguageLexer.java
  de.dlr.sc.virsat.model.concept.ide/src-gen/de/dlr/sc/virsat/model/concept/ide/contentassist/antlr/internal/InternalConceptLanguageParser.java
  de.dlr.sc.virsat.model.concept.ui/src-gen/de/dlr/sc/virsat/model/concept/ui/contentassist/AbstractConceptLanguageProposalProvider.java
  de.dlr.sc.virsat.model.concept/src-gen/de/dlr/sc/virsat/model/concept/ConceptLanguage.xtextbin
  de.dlr.sc.virsat.model.concept/src-gen/de/dlr/sc/virsat/model/concept/parser/antlr/internal/InternalConceptLanguage.g
  de.dlr.sc.virsat.model.concept/src-gen/de/dlr/sc/virsat/model/concept/parser/antlr/internal/InternalConceptLanguage.tokens
  de.dlr.sc.virsat.model.concept/src-gen/de/dlr/sc/virsat/model/concept/parser/antlr/internal/InternalConceptLanguageLexer.java
  de.dlr.sc.virsat.model.concept/src-gen/de/dlr/sc/virsat/model/concept/parser/antlr/internal/InternalConceptLanguageParser.java
  de.dlr.sc.virsat.model.concept/src-gen/de/dlr/sc/virsat/model/concept/serializer/ConceptLanguageSemanticSequencer.java
  de.dlr.sc.virsat.model.concept/src-gen/de/dlr/sc/virsat/model/concept/services/ConceptLanguageGrammarAccess.java
  de.dlr.sc.virsat.model.concept/src/de/dlr/sc/virsat/model/concept/ConceptLanguage.xtext
  de.dlr.sc.virsat.model.concept/xtend-gen/de/dlr/sc/virsat/model/concept/generator/beans/GenerateCategoryBeans.java
  de.dlr.sc.virsat.model.concept/xtend-gen/de/dlr/sc/virsat/model/concept/generator/tests/GenerateCategoryTests.java
  de.dlr.sc.virsat.model.concept/xtend-gen/de/dlr/sc/virsat/model/concept/generator/tests/GenerateStructuralElementTests.java
  de.dlr.sc.virsat.model.edit/plugin.properties
  de.dlr.sc.virsat.model.edit/src-gen/de/dlr/sc/virsat/model/dvlm/concepts/provider/ConceptItemProvider.java
  de.dlr.sc.virsat.model/model/dvlm.ecore
  de.dlr.sc.virsat.model/model/dvlm.history
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/concepts/Concept.java
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/concepts/ConceptsPackage.java
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/concepts/impl/ConceptImpl.java
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/concepts/impl/ConceptsPackageImpl.java
  de.dlr.sc.virsat.uiengine.ui/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.uiengine.ui/plugin.xml
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/general/UiSnippetBetaWarning.java
  launchers/VirSat Core Application (IgnoreBeta).launch
Labels: ui

#233 Feature/task 227 integrate the phase b
  de.dlr.sc.virsat.javadoc.api/build.properties
  de.dlr.sc.virsat.javadoc.api/plugin.xml
  de.dlr.sc.virsat.model.extension.funcelectrical/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.p2updatesite/category.xml
  de.dlr.sc.virsat.product/virsat_core.product
  de.dlr.sc.virsat.target/tmodel-src/core_development.tmodel
  de.dlr.sc.virsat.target/tmodel-src/core_integration.tmodel
  launchers/VirSat Core Application (SuperUser).launch
  launchers/VirSat Core Application (other).launch
  launchers/VirSat Core Application (user).launch
  pom.xml
Labels: build

#218 Feature/task 79 navigator multiline cut
  de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/dvlm/categories/propertyinstances/provider/DVLMValuePropertyInstanceItemProviderTest.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/dvlm/categories/propertyinstances/provider/DVLMValuePropertyInstanceItemProvider.java
Labels: comfort/usability, ui

#247 Feature/task 241 create level checker
  de.dlr.sc.virsat.model.edit/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/structural/level/HasLevelTreeTraverserMatcher.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/structural/level/HierarchyLevelChecker.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/structural/level/IHierarchyLevel.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/concept/types/structural/level/HierarchyLevelCheckerTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/concept/types/structural/tree/BeanStructuralTreeTraverserTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/test/AllTests.java
Labels: feature
