Repository virtualsatellite/VirtualSatellite4-Core, pull requests merged in 2019-09, with the labels that each got.

#251 Added layout for Developer Manual
  de.dlr.sc.virsat.docs.feature/src/docs/VirSat_Core_Developer_Manual.adoc
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterIdeInstallation/DownloadIdeRelease.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterIdeInstallation/ExecuteEclipse.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterIdeInstallation/UnzipIde.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterIdeInstallation/VirtualSatelliteIdeStarted.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/title/VirtualSatellite_Developing.jpg
Labels: comfort/usability, feature, manual

#258 Updated script to dismiss warn - (Task #257)
  bash/maven_build.sh
Labels: build, quality

#262 Refactored VirSatDanglingReferencesTest to use AProjectTestCase
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/resources/VirSatDanglingReferencesTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/resources/VirSatProjectResourceTest.java
Labels: build

#264 Improving SWT and Surefire test output - (Task #263)
  de.dlr.sc.virsat.swtbot.test/pom.xml
  maven/pom.xml
Labels: build

#261 Load referenced DMF resource and resolve proxy - (Task #259)
  de.dlr.sc.virsat.model.extension.tests.edit.test/src/de/dlr/sc/virsat/model/dvlm/dmf/DmfResourceTest.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/resources/dmf/DmfResource.java
Labels: bug

#266 Changed Display Sync Bahvior for SWTBot Tests - (Task #265)
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ASwtBotTestCase.java
Labels: bug, quality

#270 Updated product Definition - (Task #269)
  de.dlr.sc.virsat.product/virsat_core.product
Labels: bug, build

#275 Add requirements feature to p2 site and tmodel - (Task #274)
  de.dlr.sc.virsat.p2updatesite/category.xml
  de.dlr.sc.virsat.target/tmodel-src/core_development.tmodel
  de.dlr.sc.virsat.target/tmodel-src/core_integration.tmodel
  de.dlr.sc.virsat.test.feature/feature.xml
Labels: build

#273 Trying to improve cleanup - (Task #271)
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/test/AProjectTestCase.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/editingDomain/VirSatEditingDomainRegistry.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/editingDomain/VirSatTransactionalEditingDomain.java
Labels: quality

#278 Initial Developer Manual & external Libraries for windows and linux
  de.dlr.sc.virsat.docs.feature/pom.xml
  de.dlr.sc.virsat.docs.feature/src/docs/VirSat_Core_Developer_Manual.adoc
  de.dlr.sc.virsat.docs.feature/src/docs/VirSat_Core_User_Manual.adoc
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterExternalLibraries/BuildClassPathEditor.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterExternalLibraries/BuildPropertiesExternal.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterExternalLibraries/ManifestRuntimeTab.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterExternalLibraries/TheJsonSimpleTPL.png
Labels: manual

#288 Minor Improvements to Travis-CI
  .travis.yml
Labels: bug, build
