Repository virtualsatellite/VirtualSatellite4-Core, pull requests merged in 2020-10, with the labels that each got.

#741 Added test cases for idempotency and dynamic lists for BeanCategoryAssignments unmarshalling
  de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryCompositionArray_Marshaling.json
  de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryReferenceArray_Marshaling.json
  de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryReferenceArray_Marshaling_ChangeReference.json
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/model/json/TestCategoryAllPropertyTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/model/json/TestCategoryBeanATest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/model/json/TestCategoryCompositionArrayTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/model/json/TestCategoryCompositionTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/model/json/TestCategoryIntrinsicArrayTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/model/json/TestCategoryReferenceArrayTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/model/json/TestCategoryReferenceTest.java
Labels: Server, quality

#753 SWTBot Test case for FEA exports and imports with Excel
  de.dlr.sc.virsat.excel.ui/src/de/dlr/sc/virsat/excel/ui/wizards/ExportPage.java
  de.dlr.sc.virsat.excel.ui/src/de/dlr/sc/virsat/excel/ui/wizards/ExportWizard.java
  de.dlr.sc.virsat.excel.ui/src/de/dlr/sc/virsat/excel/ui/wizards/ImportPage.java
  de.dlr.sc.virsat.excel.ui/src/de/dlr/sc/virsat/excel/ui/wizards/ImportWizard.java
  de.dlr.sc.virsat.model.extension.funcelectrical/src/de/dlr/sc/virsat/model/extension/funcelectrical/excel/importer/FuncElecImporter.java
  de.dlr.sc.virsat.model.extension.funcelectrical/src/de/dlr/sc/virsat/model/extension/funcelectrical/excel/importer/ImportValidator.java
  de.dlr.sc.virsat.swtbot.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ExporterImporterWizardTest.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ProjectUiAllTests.java
Labels: build

#754 Fixed position correction int FEA diagrams of interface ends on right side of an element - (Task #749)
  de.dlr.sc.virsat.model.extension.funcelectrical.ui/src/de/dlr/sc/virsat/model/extension/funcelectrical/ui/diagram/features/elements/ElementLayoutFeature.java
  de.dlr.sc.virsat.model.extension.funcelectrical.ui/src/de/dlr/sc/virsat/model/extension/funcelectrical/ui/diagram/features/interfaceends/InterfaceEndAddFeature.java
  de.dlr.sc.virsat.model.extension.funcelectrical.ui/src/de/dlr/sc/virsat/model/extension/funcelectrical/ui/diagram/features/interfaceends/InterfaceEndMoveFeature.java
  de.dlr.sc.virsat.model.extension.funcelectrical.ui/src/de/dlr/sc/virsat/model/extension/funcelectrical/ui/diagram/utils/DiagramUtils.java
Labels: bug

#758 SWTBot Test case for FEA exports into HTML
  de.dlr.sc.virsat.model.extension.funcelectrical.ui/src/de/dlr/sc/virsat/model/extension/funcelectrical/ui/wizards/HTMLExportPage.java
  de.dlr.sc.virsat.model.extension.funcelectrical/src/de/dlr/sc/virsat/model/extension/funcelectrical/html/ExportHelper.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ExporterImporterWizardTest.java
Labels: quality

#765 Added VirSat diagram feature provider with patterns - (Task #763)
  de.dlr.sc.virsat.graphiti.ui/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.graphiti.ui/src/de/dlr/sc/virsat/graphiti/ui/diagram/feature/VirsatDiagramFeatureProviderWithPatterns.java
Labels: easy, feature

#767 Added method to provide auto update functionality - (Task #766)
  de.dlr.sc.virsat.graphiti.ui/src/de/dlr/sc/virsat/graphiti/ui/diagram/editor/VirSatDiagramUpdateBehavior.java
Labels: feature

#752 Add SWTBot test cases for drill down - (Task #745)
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/EditorTest.java
Labels: quality

#755 Extended functionality to support connection colors - (Task #750)
  de.dlr.sc.virsat.graphiti.ui/src/de/dlr/sc/virsat/graphiti/ui/diagram/feature/VirSatChangeColorFeature.java
  de.dlr.sc.virsat.model.extension.funcelectrical.ui/src/de/dlr/sc/virsat/model/extension/funcelectrical/ui/diagram/features/InterfaceDiagramFeatureProvider.java
Labels: feature

#772 Increased test timeout value for SWTBot tests in pom - (Task #771)
  de.dlr.sc.virsat.swtbot.test/pom.xml
Labels: build

#760 Feature/task 751 swt bot test cases for properties
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ASwtBotTestCase.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/EditorTest.java
Labels: quality

#768 SWTBot Test for Exporting and Importing .mat files
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ExporterImporterWizardTest.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/wizard/AImportExportPage.java
Labels: quality

#770 Feature/task 756 swt bot tests for arrays
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ASwtBotTestCase.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/EditorTest.java
Labels: quality

#773 Feature/task 764 swt bot test case for categories with cardinality 1
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/EditorTest.java
Labels: quality

#778 SWTBot Test for CAD Export/Import
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ExporterImporterWizardTest.java
Labels: quality

#759 Added PowerSummaryTest - (Task #746)
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/PowerSummaryTest.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ProjectUiAllTests.java
Labels: quality

#777 Feature/task 774 swt bot to check that
  de.dlr.sc.virsat.model.ext.core.edit.test/about.html
  de.dlr.sc.virsat.model.ext.core.edit.test/build.properties
  de.dlr.sc.virsat.model.ext.core.edit/about.html
  de.dlr.sc.virsat.model.ext.core.edit/build.properties
  de.dlr.sc.virsat.model.ext.core.test/about.html
  de.dlr.sc.virsat.model.ext.core.test/build.properties
  de.dlr.sc.virsat.model.ext.core/about.html
  de.dlr.sc.virsat.model.ext.core/build.properties
  de.dlr.sc.virsat.model.extension.funcelectrical/plugin.properties
  de.dlr.sc.virsat.model.extension.tests.edit/plugin.properties
  de.dlr.sc.virsat.model.extension.tests.ui/build.properties
  de.dlr.sc.virsat.model.extension.tests/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.tests/build.properties
  de.dlr.sc.virsat.model.extension.tests/plugin.properties
  de.dlr.sc.virsat.model.external.tests.edit/about.html
  de.dlr.sc.virsat.model.external.tests.edit/build.properties
  de.dlr.sc.virsat.model.external.tests/about.html
  de.dlr.sc.virsat.model.external.tests/build.properties
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ASwtBotTestCase.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/LicenseTest.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ProjectUiAllTests.java
Labels: quality

#785 Fix NPE in requirements attribute label provider - (Task #697)
  de.dlr.sc.virsat.model.extension.requirements.ui/src/de/dlr/sc/virsat/model/extension/requirements/ui/provider/RequirementsAttributeDefinitionTableLabelProvider.java
Labels: bug, ui

#788 Refactor Initialization of Requirements Verification
  de.dlr.sc.virsat.model.extension.requirements.ui/src/de/dlr/sc/virsat/model/extension/requirements/ui/snippet/UiSnippetTableRequirementVerificationDefaultVerification.java
Labels: quality

#786 Implemented Rename and ChangeValue handlers and F2 behavior
  de.dlr.sc.virsat.project.ui/plugin.xml
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/handler/ChangeValueHandler.java
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/handler/RenameHandler.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/AUiSnippetGenericTable.java
Labels: comfort/usability, feature

#793 Fixed app activation to stop producing warnings - (Task #733)
  de.dlr.sc.virsat.apps.test/resources/.empty
  de.dlr.sc.virsat.apps.test/resources/expectedGeneratorContent/AppManifest.MF
  de.dlr.sc.virsat.apps.test/src/de/dlr/sc/virsat/apps/initializer/ContentManifestMfTest.java
  de.dlr.sc.virsat.apps.test/src/de/dlr/sc/virsat/apps/initializer/VirsatAppsInititalizerTest.java
  de.dlr.sc.virsat.apps/src/de/dlr/sc/virsat/apps/initializer/ContentManifestMf.xtend
  de.dlr.sc.virsat.apps/src/de/dlr/sc/virsat/apps/initializer/VirsatAppsInitializer.java
  de.dlr.sc.virsat.apps/xtend-gen/de/dlr/sc/virsat/apps/initializer/ContentManifestMf.java
Labels: bug

#747 PR #1 Low Level API - Add CAs and Properties
  .codebeatsettings
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/factory/BeanPropertyFactory.java
  de.dlr.sc.virsat.model/src/de/dlr/sc/virsat/model/dvlm/tree/ITreeTraverserMatcher.java
  de.dlr.sc.virsat.server.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/dataaccess/RepositoryUtilityTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/dataaccess/TransactionalJsonProviderTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/AccessTestResourceTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/ModelAccessResourceTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/test/AGitAndJettyServerTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/test/AServerRepositoryTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/test/AllTests.java
  de.dlr.sc.virsat.server/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/dataaccess/RepositoryUtility.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/dataaccess/TransactionalJsonProvider.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/ModelAccessResource.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/servlet/VirSatModelAccessServlet.java
Labels: Server, feature

#748 PR #2 Low Level API - Add SEIs
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/dataaccess/TransactionalJsonProviderTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/ModelAccessResourceTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/test/AGitAndJettyServerTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/test/AServerRepositoryTest.java
  de.dlr.sc.virsat.server/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/dataaccess/TransactionalJsonProvider.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/ModelAccessResource.java
Labels: Server, feature
