Repository virtualsatellite/VirtualSatellite4-Core, pull requests merged in 2020-12, with the labels that each got.

#860 Added kempra to known_authors and kemp_ra to mailmap
  .github/workflows/main.yml
  .mailmap
  bash/verify_commit_authors.sh
  known_authors.txt
Labels: build

#847 Add two Category´s (CostEquipment, CostSummary) - (Task #839)
  de.dlr.sc.virsat.model.extension.budget.cost.test/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/model/ACostEquipmentTest.java
  de.dlr.sc.virsat.model.extension.budget.cost.test/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/model/ACostSummaryTest.java
  de.dlr.sc.virsat.model.extension.budget.cost.test/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/test/AllTestsGen.java
  de.dlr.sc.virsat.model.extension.budget.cost.test/src/de/dlr/sc/virsat/model/extension/budget/cost/model/CostEquipmentTest.java
  de.dlr.sc.virsat.model.extension.budget.cost.test/src/de/dlr/sc/virsat/model/extension/budget/cost/model/CostSummaryTest.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/plugin.xml
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/ui/command/ACreateAddCostEquipmentCommand.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/ui/command/ACreateAddCostSummaryCommand.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/ui/handler/AAddCostEquipmentHandler.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/ui/handler/AAddCostSummaryHandler.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/ui/snippet/AUiSnippetSectionCostEquipment.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/ui/snippet/AUiSnippetSectionCostSummary.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/ui/snippet/AUiSnippetTableCostEquipment.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/ui/snippet/AUiSnippetTableCostSummary.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src/de/dlr/sc/virsat/model/extension/budget/cost/ui/command/CreateAddCostEquipmentCommand.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src/de/dlr/sc/virsat/model/extension/budget/cost/ui/command/CreateAddCostSummaryCommand.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src/de/dlr/sc/virsat/model/extension/budget/cost/ui/handler/AddCostEquipmentHandler.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src/de/dlr/sc/virsat/model/extension/budget/cost/ui/handler/AddCostSummaryHandler.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src/de/dlr/sc/virsat/model/extension/budget/cost/ui/snippet/UiSnippetSectionCostEquipment.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src/de/dlr/sc/virsat/model/extension/budget/cost/ui/snippet/UiSnippetSectionCostSummary.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src/de/dlr/sc/virsat/model/extension/budget/cost/ui/snippet/UiSnippetTableCostEquipment.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src/de/dlr/sc/virsat/model/extension/budget/cost/ui/snippet/UiSnippetTableCostSummary.java
  de.dlr.sc.virsat.model.extension.budget.cost/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.budget.cost/concept/concept_v1_0.xmi
  de.dlr.sc.virsat.model.extension.budget.cost/plugin.xml
  de.dlr.sc.virsat.model.extension.budget.cost/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/model/AACostParameters.java
  de.dlr.sc.virsat.model.extension.budget.cost/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/model/ACostEquipment.java
  de.dlr.sc.virsat.model.extension.budget.cost/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/model/ACostSummary.java
  de.dlr.sc.virsat.model.extension.budget.cost/src/de/dlr/sc/virsat/model/extension/budget/cost/model/ACostParameters.java
  de.dlr.sc.virsat.model.extension.budget.cost/src/de/dlr/sc/virsat/model/extension/budget/cost/model/CostEquipment.java
  de.dlr.sc.virsat.model.extension.budget.cost/src/de/dlr/sc/virsat/model/extension/budget/cost/model/CostSummary.java
Labels: feature

#865 Commiting fully regnerated code - (Task #864)
  de.dlr.sc.virsat.model.extension.requirements/plugin.xml
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/AAttributeValue.java
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ADefaultVerification.java
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/AEnumerationDefinition.java
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/AEnumerationLiteral.java
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/AExistenceVerification.java
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/AIVerification.java
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/AModelVerification.java
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ARequirement.java
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ARequirementAttribute.java
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ARequirementGroup.java
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ARequirementLink.java
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ARequirementObject.java
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ARequirementType.java
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ARequirementsConfiguration.java
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ARequirementsSpecification.java
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/AVerificationConfiguration.java
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/AVerificationType.java
  de.dlr.sc.virsat.model.extension.tests/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.tests/build.properties
  de.dlr.sc.virsat.model.extension.tests/plugin.properties
Labels: build

#867 Restore the Concep.concept in the Cost-Concept - (Task #866)
  de.dlr.sc.virsat.model.extension.budget.cost.test/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/model/ACostEquipmentTest.java
  de.dlr.sc.virsat.model.extension.budget.cost.test/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/model/ACostSummaryTest.java
  de.dlr.sc.virsat.model.extension.budget.cost.test/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/model/AInterfaceEndTest.java
  de.dlr.sc.virsat.model.extension.budget.cost.test/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/model/AInterfaceTest.java
  de.dlr.sc.virsat.model.extension.budget.cost.test/src/de/dlr/sc/virsat/model/extension/budget/cost/model/InterfaceEndTest.java
  de.dlr.sc.virsat.model.extension.budget.cost.test/src/de/dlr/sc/virsat/model/extension/budget/cost/model/InterfaceTest.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/ui/command/ACreateAddCostEquipmentCommand.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/ui/command/ACreateAddCostSummaryCommand.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/ui/command/ACreateAddInterfaceCommand.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/ui/command/ACreateAddInterfaceEndCommand.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/ui/handler/AAddCostEquipmentHandler.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/ui/handler/AAddCostSummaryHandler.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/ui/handler/AAddInterfaceEndHandler.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/ui/handler/AAddInterfaceHandler.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/ui/snippet/AUiSnippetSectionCostEquipment.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/ui/snippet/AUiSnippetSectionCostSummary.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/ui/snippet/AUiSnippetSectionInterface.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/ui/snippet/AUiSnippetSectionInterfaceEnd.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/ui/snippet/AUiSnippetTableCostEquipment.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/ui/snippet/AUiSnippetTableCostSummary.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/ui/snippet/AUiSnippetTableInterface.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/ui/snippet/AUiSnippetTableInterfaceEnd.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src/de/dlr/sc/virsat/model/extension/budget/cost/ui/command/CreateAddInterfaceCommand.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src/de/dlr/sc/virsat/model/extension/budget/cost/ui/command/CreateAddInterfaceEndCommand.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src/de/dlr/sc/virsat/model/extension/budget/cost/ui/handler/AddInterfaceEndHandler.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src/de/dlr/sc/virsat/model/extension/budget/cost/ui/handler/AddInterfaceHandler.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src/de/dlr/sc/virsat/model/extension/budget/cost/ui/snippet/UiSnippetSectionInterface.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src/de/dlr/sc/virsat/model/extension/budget/cost/ui/snippet/UiSnippetSectionInterfaceEnd.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src/de/dlr/sc/virsat/model/extension/budget/cost/ui/snippet/UiSnippetTableInterface.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src/de/dlr/sc/virsat/model/extension/budget/cost/ui/snippet/UiSnippetTableInterfaceEnd.java
  de.dlr.sc.virsat.model.extension.budget.cost/concept/concept.concept
  de.dlr.sc.virsat.model.extension.budget.cost/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.budget.cost/concept/concept_v1_0.xmi
  de.dlr.sc.virsat.model.extension.budget.cost/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/model/AACostParameters.java
  de.dlr.sc.virsat.model.extension.budget.cost/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/model/ACostEquipment.java
  de.dlr.sc.virsat.model.extension.budget.cost/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/model/ACostSummary.java
  de.dlr.sc.virsat.model.extension.budget.cost/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/model/AInterface.java
  de.dlr.sc.virsat.model.extension.budget.cost/src-gen/de/dlr/sc/virsat/model/extension/budget/cost/model/AInterfaceEnd.java
  de.dlr.sc.virsat.model.extension.budget.cost/src/de/dlr/sc/virsat/model/extension/budget/cost/model/Interface.java
  de.dlr.sc.virsat.model.extension.budget.cost/src/de/dlr/sc/virsat/model/extension/budget/cost/model/InterfaceEnd.java
Labels: feature

#857 Update the icons of CostEquipment and CostSummary
  de.dlr.sc.virsat.model.extension.budget.cost.ui/resources/icons/ACostParameters.gif
  de.dlr.sc.virsat.model.extension.budget.cost.ui/resources/icons/ACostParameters_disabled.gif
  de.dlr.sc.virsat.model.extension.budget.cost.ui/resources/icons/CostEquipment.gif
  de.dlr.sc.virsat.model.extension.budget.cost.ui/resources/icons/CostEquipment_disabled.gif
  de.dlr.sc.virsat.model.extension.budget.cost.ui/resources/icons/CostSummary.gif
  de.dlr.sc.virsat.model.extension.budget.cost.ui/resources/icons/CostSummary_disabled.gif
Labels: feature

#863 Improve Stability of tests
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/project/editingDomain/VirSatTransactionalEditingDomainNonDVLMTest.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/versioningbackend/AVersioningBackendTest.java
Labels: quality

#868 Expanded Visualisation Concept chapter in User Manual - (Task #854)
  de.dlr.sc.virsat.docs.feature/src/docs/VirSat_Core_User_Manual.adoc
Labels: manual

#874 Add Paulina to known authors
  .mailmap
  known_authors.txt
Labels: build

#871 Fixed Problems on GitHub Actions build on Ubuntu 18.04 nodes
  .github/workflows/main.yml
  bash/maven_build.sh
  bash/setup.sh
  bash/setup_environment.sh
  de.dlr.sc.virsat.model.extension.tests.edit.test/src/.empty_folder
  de.dlr.sc.virsat.model.extension.tests.edit.test/src/de/dlr/sc/virsat/model/extension/tests/edit/test/AllTests.java
  de.dlr.sc.virsat.model.extension.tests.edit.test/src/de/dlr/sc/virsat/model/extension/tests/edit/test/TemplateTest.java
  de.dlr.sc.virsat.model.extension.tests.edit.test/src/de/dlr/sc/virsat/model/extension/tests/model/AConceptTestCase.java
  de.dlr.sc.virsat.model.extension.tests.edit.test/src/de/dlr/sc/virsat/project/resources/dmf/DmfResourceTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/project/resources/dmf/DmfResourceTest.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/resources/dmf/DmfResource.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/EditorTest.java
  launchers/SwtBot Tests.launch
  launchers/VirSat Core Application (SwtBot).launch
  maven/pom.xml
Labels: bug, build, easy

#877 Added George to known authors - (Task #876)
  known_authors.txt
Labels: build

#888 Improved build stability
  bash/setup.sh
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/project/resources/dmf/DmfResourceTest.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/RoleManagementTest.java
Labels: build

#814 Added an additional type field to JSON property beans
  de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/dvlm/json/BeanPropertyTypeAdapterTest.java
  de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/edit/test/AllTests.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/ABeanProperty.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyBoolean.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyComposed.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyEReference.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyEnum.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyFloat.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyInt.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyReference.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyResource.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyString.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyType.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/dvlm/json/BeanPropertyTypeAdapter.java
  de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryAllProperty_Marshaling.json
  de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryAllProperty_Marshaling_Defaults.json
  de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryCompositionArray_Marshaling.json
  de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryCompositionArray_Marshaling_NullComposition.json
  de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryComposition_Marshaling.json
  de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryIntrinsicArray_Marshaling.json
  de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryReferenceArray_Marshaling.json
  de.dlr.sc.virsat.model.extension.tests.test/resources/json/TestCategoryReferenceArray_Marshaling_NullReference.json
Labels: Server, feature

#884 Added George to mailmap
  .mailmap
Labels: build

#889 Created chapter for describing the Concept Language
  de.dlr.sc.virsat.docs.feature/src/docs/VirSat_Core_Developer_Manual.adoc
Labels: manual

#886 Developer manual concept creation
  de.dlr.sc.virsat.docs.feature/src/docs/VirSat_Core_Developer_Manual.adoc
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterConceptCreation/button_toggle_generation.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterConceptCreation/concept_creation.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterConceptCreation/concept_wizard_selection.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterConceptCreation/generated_plugins.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterConceptCreation/main_plugin.png
Labels: manual

#881 Add user manual for functional electrical architecture
  de.dlr.sc.virsat.docs.feature/src/docs/VirSat_Core_User_Manual.adoc
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionFEA/AddInterfaceType.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionFEA/AddMechanicalEngineering.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionFEA/Diagram.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionFEA/DocumentsElement.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionFEA/InterfaceEnd.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionFEA/InterfaceInTheDiagram.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionFEA/InterfaceType.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionFEA/NewElement.PNG
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionFEA/VoltageSpecificationPowerInterfaceType.png
Labels: manual

#861 Add manual section for requirements
  de.dlr.sc.virsat.docs.feature/src/docs/VirSat_Core_User_Manual.adoc
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/ImportMenuRequirements.jpg
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionRequirements/ActivateConcepts.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionRequirements/AddRequirement.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionRequirements/AddRequirementType.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionRequirements/AddValues.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionRequirements/AddVerification.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionRequirements/AddVerificationConfiguration.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionRequirements/AddVerificationType.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionRequirements/ChooseRequirementType.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionRequirements/ConfigureVerificationType.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionRequirements/CreateRequirementGroup.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionRequirements/CreateRequirementSpec.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionRequirements/CsvImportEnumeration.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionRequirements/CsvImportStartPage.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionRequirements/CsvImportStartPageExisitingType.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionRequirements/CsvImportTargetPage.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionRequirements/CsvImportTypeCustomizationPage.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionRequirements/CsvImportTypeMappingPage.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionRequirements/DrillDownReqGroup.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionRequirements/ImportMenuRequirements.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionRequirements/ImportWizard.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionRequirements/OpenRequirementEditor.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionRequirements/RequirementStatus.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterModeling/subsectionRequirements/SpecifyRequirementTypeNameAndAttributes.png
Labels: manual

#875 Added REST server manual
  de.dlr.sc.virsat.docs.feature/src/docs/VirSat_Core_Server_Manual.adoc
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterServerComponents/REST_server_components.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterServerOverview/REST_server_overview.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/title/VirtualSatellite_Server.jpg
Labels: Server, manual

#878 Features/task 850 create a concept chapter for state machines
  de.dlr.sc.virsat.docs.feature/src/docs/VirSat_Core_User_Manual.adoc
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterStateMachines/AOCSSystemStateMachine.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterStateMachines/AOCSTransitionsAndTriggerEvents.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterStateMachines/AddState.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterStateMachines/AddStateMachine.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterStateMachines/AddStateMachineConcept.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterStateMachines/AddTransitionTriggerEvent.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterStateMachines/AddingSystemStateMachine.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterStateMachines/AssigningTriggers.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterStateMachines/CreateCamStateMachine.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterStateMachines/CreateSubcomponentsOfSystem.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterStateMachines/CreatingAOCSElementConfiguration.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterStateMachines/DiagramEditor.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterStateMachines/ExtractingExcelTables.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterStateMachines/Open Editor.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterStateMachines/OpenDiagramEditor.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterStateMachines/OpenedWizardForTriggerActions.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterStateMachines/UpdateStateMachine.png
  known_authors.txt
Labels: manual

#892 Feature/task 891 multiline state labels
  de.dlr.sc.virsat.graphiti.test/src/de/dlr/sc/virsat/graphiti/label/MultilineLabelFormatterTest.java
  de.dlr.sc.virsat.graphiti.test/src/de/dlr/sc/virsat/graphiti/test/AllTests.java
  de.dlr.sc.virsat.graphiti.ui/src/de/dlr/sc/virsat/graphiti/ui/diagram/feature/BeanDirectEditNameFeature.java
  de.dlr.sc.virsat.graphiti/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.graphiti/src/de/dlr/sc/virsat/graphiti/label/MultilineLabelFormatter.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/stateMachines/StateMachineUpdateFeature.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/states/StateAddFeature.java
Labels: comfort/usability, ui

#833 Add external lib for swagger (PR1)
  de.dlr.sc.virsat.external.lib.feature/feature.xml
  de.dlr.sc.virsat.external.lib.swagger/.checkstyle
  de.dlr.sc.virsat.external.lib.swagger/.classpath
  de.dlr.sc.virsat.external.lib.swagger/.project
  de.dlr.sc.virsat.external.lib.swagger/.settings/edu.umd.cs.findbugs.core.prefs
  de.dlr.sc.virsat.external.lib.swagger/.settings/org.eclipse.core.resources.prefs
  de.dlr.sc.virsat.external.lib.swagger/.settings/org.eclipse.core.runtime.prefs
  de.dlr.sc.virsat.external.lib.swagger/.settings/org.eclipse.jdt.core.prefs
  de.dlr.sc.virsat.external.lib.swagger/.settings/org.eclipse.m2e.core.prefs
  de.dlr.sc.virsat.external.lib.swagger/.settings/org.eclipse.mylyn.team.ui.prefs
  de.dlr.sc.virsat.external.lib.swagger/.settings/org.eclipse.pde.prefs
  de.dlr.sc.virsat.external.lib.swagger/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.external.lib.swagger/about.html
  de.dlr.sc.virsat.external.lib.swagger/about_files/LICENSE
  de.dlr.sc.virsat.external.lib.swagger/about_files/THIRD-PARTY.txt
  de.dlr.sc.virsat.external.lib.swagger/build.properties
  de.dlr.sc.virsat.external.lib.swagger/externalLib/maven/swagger-annotations.jar
  de.dlr.sc.virsat.external.lib.swagger/pom.xml
  de.dlr.sc.virsat.external.lib.swagger/src/de/dlr/sc/virsat/external/lib/swagger/Activator.java
  de.dlr.sc.virsat.model.edit/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/ABeanObject.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/IBeanObject.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/category/ABeanCategoryAssignment.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/category/IBeanCategoryAssignment.java
  de.dlr.sc.virsat.server/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/ModelAccessResource.java
  launchers/VirSat Core Application (user).launch
  pom.xml
Labels: Server, feature

#894 Uploading all surefire reports upon CI failure - (Task #893)
  .github/workflows/main.yml
Labels: build

#901 Hide composed property instance
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/contentProvider/VirSatProjectContentProvider.java
Labels: comfort/usability, ui

#869 Add Euro in Unit-Management - (Task #841)
  de.dlr.sc.virsat.model.extension.budget.cost.test/src/de/dlr/sc/virsat/model/extension/budget/cost/test/AllTests.java
  de.dlr.sc.virsat.model.extension.budget.cost.test/src/de/dlr/sc/virsat/model/extension/budget/cost/unit/EuroUnitCreatorTest.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src/de/dlr/sc/virsat/model/extension/budget/cost/ui/snippet/UiSnippetTableCostEquipment.java
  de.dlr.sc.virsat.model.extension.budget.cost.ui/src/de/dlr/sc/virsat/model/extension/budget/cost/ui/snippet/UiSnippetTableCostSummary.java
  de.dlr.sc.virsat.model.extension.budget.cost/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.budget.cost/src/de/dlr/sc/virsat/model/extension/budget/cost/unit/EuroUnitCreator.java
Labels: feature

#903 Fix swagger dependencies for down stream projects - (Task #902)
  de.dlr.sc.virsat.external.lib.feature/feature.xml
  de.dlr.sc.virsat.model.edit/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.feature/feature.xml
Labels: bug, build

#835 Generate static Swagger documentation with Maven (PR2)
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/ABeanObject.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/IBeanObject.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/category/IBeanCategoryAssignment.java
  de.dlr.sc.virsat.model/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.server/.classpath
  de.dlr.sc.virsat.server/build.properties
  de.dlr.sc.virsat.server/doc-gen/definitions.adoc
  de.dlr.sc.virsat.server/doc-gen/overview.adoc
  de.dlr.sc.virsat.server/doc-gen/paths.adoc
  de.dlr.sc.virsat.server/doc-gen/security.adoc
  de.dlr.sc.virsat.server/doc-gen/swagger.json
  de.dlr.sc.virsat.server/doc-gen/swagger.yaml
  de.dlr.sc.virsat.server/pom.xml
  de.dlr.sc.virsat.server/src-maven/model.substitution
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/jetty/VirSatJettyServer.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/ModelAccessResource.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/servlet/VirSatModelAccessServlet.java
Labels: Server, feature
