Repository virtualsatellite/VirtualSatellite4-Core, pull requests merged in 2020-07, with the labels that each got.

#670 SWTBot Tests for SVN and Git Versioning Backend
  de.dlr.sc.virsat.build.test/src/de/dlr/sc/virsat/build/inheritance/VirSatInheritanceBuilderTest.java
  de.dlr.sc.virsat.build.test/src/de/dlr/sc/virsat/build/inheritance/VirSatTransactionalBuilderTest.java
  de.dlr.sc.virsat.build.test/src/de/dlr/sc/virsat/build/test/AllTests.java
  de.dlr.sc.virsat.build.test/src/de/dlr/sc/virsat/build/validator/VirSatValidatorBuilderTest.java
  de.dlr.sc.virsat.build/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.build/src/de/dlr/sc/virsat/build/inheritance/AVirSatBuilder.java
  de.dlr.sc.virsat.build/src/de/dlr/sc/virsat/inheritance/InheritanceHelper.java
  de.dlr.sc.virsat.model.extension.visualisation.test/src/de/dlr/sc/virsat/model/extension/visualisation/test/AllTests.java
  de.dlr.sc.virsat.model.extension.visualisation.test/src/de/dlr/sc/virsat/model/extension/visualisation/treemanager/networking/SceneGraphClientTest.java
  de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/Activator.java
  de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/vtkClient/VtkClientVisUpdateHandler.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/editingDomain/VirSatEditingDomainRegistryTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/structure/VirSatProjectCommonsTest.java
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/labelProvider/VirSatTransactionalAdapterFactoryLabelProvider.java
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/VirSatNavigator.java
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/contentProvider/VirSatWorkspaceContentProvider.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/editingDomain/VirSatEditingDomainRegistry.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/editingDomain/VirSatTransactionalEditingDomain.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/structure/VirSatProjectCommons.java
  de.dlr.sc.virsat.swtbot.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.swtbot.test/pom.xml
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ASwtBotTestCase.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/CutCopyDeleteUndoTest.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ProjectUiAllTests.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/versioningbackend/AVersioningBackendTest.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/versioningbackend/GitVersioningBackendTest.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/versioningbackend/SvnVersioningBackendTest.java
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/handler/AVersionControlCommitHandler.java
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/handler/AVersionControlUpdateHandler.java
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/util/VersionControlJob.java
  launchers/VirSat Core Application (SwtBot).launch
  maven/pom.xml
Labels: bug, build, quality

#672 Exchanged write access checks in snippet for equation section
  de.dlr.sc.virsat.model.calculation.ui/src/de/dlr/sc/virsat/model/calculation/ui/editor/snippet/UiSnippetEquations.java
Labels: bug

#673 Feature/task 663 add bean list for bea
  de.dlr.sc.virsat.model.concept.test/resources/expectedOutputFilesForGenerators/ACategoryBeanTypesAndReferencesArrays.java
  de.dlr.sc.virsat.model.concept/src/de/dlr/sc/virsat/model/concept/generator/beans/GenerateCategoryBeans.xtend
  de.dlr.sc.virsat.model.concept/xtend-gen/de/dlr/sc/virsat/model/concept/generator/beans/GenerateCategoryBeans.java
  de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/concept/lists/TypeSafeComposedPropertyBeanListTest.java
  de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/concept/lists/TypeSafeReferencePropertyBeanListTest.java
  de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/edit/test/AllTests.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/list/TypeSafeArrayInstanceList.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/list/TypeSafeComposedPropertyBeanList.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/list/TypeSafeReferencePropertyBeanList.java
Labels: feature

#605 Add trace element to requirements concept
  de.dlr.sc.virsat.model.extension.requirements.test/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ARequirementTraceTest.java
  de.dlr.sc.virsat.model.extension.requirements.test/src-gen/de/dlr/sc/virsat/model/extension/requirements/test/AllTestsGen.java
  de.dlr.sc.virsat.model.extension.requirements.test/src/de/dlr/sc/virsat/model/extension/requirements/model/RequirementTraceTest.java
  de.dlr.sc.virsat.model.extension.requirements.ui/plugin.xml
  de.dlr.sc.virsat.model.extension.requirements.ui/resources/icons/RequirementTrace.gif
  de.dlr.sc.virsat.model.extension.requirements.ui/resources/icons/RequirementTrace_disabled.gif
  de.dlr.sc.virsat.model.extension.requirements.ui/src-gen/de/dlr/sc/virsat/model/extension/requirements/ui/command/ACreateAddArrayElementTargetCommand.java
  de.dlr.sc.virsat.model.extension.requirements.ui/src-gen/de/dlr/sc/virsat/model/extension/requirements/ui/command/ACreateAddRequirementTraceCommand.java
  de.dlr.sc.virsat.model.extension.requirements.ui/src-gen/de/dlr/sc/virsat/model/extension/requirements/ui/handler/AAddRequirementTraceHandler.java
  de.dlr.sc.virsat.model.extension.requirements.ui/src-gen/de/dlr/sc/virsat/model/extension/requirements/ui/snippet/AUiSnippetSectionRequirementTrace.java
  de.dlr.sc.virsat.model.extension.requirements.ui/src-gen/de/dlr/sc/virsat/model/extension/requirements/ui/snippet/AUiSnippetTableRequirementTrace.java
  de.dlr.sc.virsat.model.extension.requirements.ui/src-gen/de/dlr/sc/virsat/model/extension/requirements/ui/snippet/AUiSnippetTableRequirementTraceTarget.java
  de.dlr.sc.virsat.model.extension.requirements.ui/src/de/dlr/sc/virsat/model/extension/requirements/ui/celleditor/RequirementTraceEditingSupport.java
  de.dlr.sc.virsat.model.extension.requirements.ui/src/de/dlr/sc/virsat/model/extension/requirements/ui/command/CreateAddArrayElementTargetCommand.java
  de.dlr.sc.virsat.model.extension.requirements.ui/src/de/dlr/sc/virsat/model/extension/requirements/ui/command/CreateAddRequirementTraceCommand.java
  de.dlr.sc.virsat.model.extension.requirements.ui/src/de/dlr/sc/virsat/model/extension/requirements/ui/handler/AddRequirementTraceHandler.java
  de.dlr.sc.virsat.model.extension.requirements.ui/src/de/dlr/sc/virsat/model/extension/requirements/ui/provider/RequirementsAttributeLabelProvider.java
  de.dlr.sc.virsat.model.extension.requirements.ui/src/de/dlr/sc/virsat/model/extension/requirements/ui/snippet/UiSnippetCustomRequirementsAttributeTable.java
  de.dlr.sc.virsat.model.extension.requirements.ui/src/de/dlr/sc/virsat/model/extension/requirements/ui/snippet/UiSnippetSectionRequirement.java
  de.dlr.sc.virsat.model.extension.requirements.ui/src/de/dlr/sc/virsat/model/extension/requirements/ui/snippet/UiSnippetSectionRequirementTrace.java
  de.dlr.sc.virsat.model.extension.requirements.ui/src/de/dlr/sc/virsat/model/extension/requirements/ui/snippet/UiSnippetTableRequirementTrace.java
  de.dlr.sc.virsat.model.extension.requirements.ui/src/de/dlr/sc/virsat/model/extension/requirements/ui/snippet/UiSnippetTableRequirementTraceTarget.java
  de.dlr.sc.virsat.model.extension.requirements.ui/src/de/dlr/sc/virsat/model/extension/requirements/ui/snippet/dialog/RequirementsTraceEditingDialog.java
  de.dlr.sc.virsat.model.extension.requirements/concept/concept.concept
  de.dlr.sc.virsat.model.extension.requirements/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.requirements/concept/concept_v0_2.xmi
  de.dlr.sc.virsat.model.extension.requirements/plugin.xml
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ARequirement.java
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ARequirementTrace.java
  de.dlr.sc.virsat.model.extension.requirements/src/de/dlr/sc/virsat/model/extension/requirements/model/RequirementTrace.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/AUiSnippetGenericTable.java
Labels: feature, ui

#590 Performance improvements by reducing number of global ResourceSet actions
  de.dlr.sc.virsat.model.calculation.ui/src/de/dlr/sc/virsat/model/calculation/ui/views/DomainRoundView.java
  de.dlr.sc.virsat.model.calculation/src/de/dlr/sc/virsat/model/calculation/compute/IncrementalEquationBuilder.java
  de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/ecore/VirSatEcoreUtilTest.java
  de.dlr.sc.virsat.model/src/de/dlr/sc/virsat/model/ecore/VirSatEcoreUtil.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/resources/VirSatResourceSetTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/structure/VirSatProjectCommonsTest.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/editingDomain/VirSatTransactionalEditingDomain.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/resources/VirSatResourceSet.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/resources/VirSatResourceSetUtil.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/structure/VirSatProjectCommons.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/structure/VirSatProjectResourceChangeListener.java
Labels: quality

#674 Synchronizing editor resource reload in workspace operation
  de.dlr.sc.virsat.build/src/de/dlr/sc/virsat/build/inheritance/VirSatInheritanceBuilder.java
  de.dlr.sc.virsat.model.calculation/src/de/dlr/sc/virsat/model/calculation/compute/IncrementalEquationBuilder.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/project/editingDomain/VirSatTransactionalEditingDomainNonDVLMTest.java
  de.dlr.sc.virsat.project.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/editingDomain/VirSatTransactionalEditingDomainResourceEventListenerTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/editingDomain/VirSatTransactionalEditingDomainTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/structure/VirSatProjectResourceChangeListenerTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/test/AProjectTestCase.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/test/AllTests.java
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/contentProvider/VirSatWorkspaceContentProvider.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/editingDomain/VirSatTransactionalEditingDomain.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/resources/VirSatResourceSet.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/structure/AVirSatProjectResourceChangeListener.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ASwtBotTestCase.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/EditorTest.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/GenericEditor.java
Labels: bug, quality

#681 Fixed resource locking in Command Stack
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/editingDomain/VirSatWorkspaceCommandStack.java
Labels: bug

#683 Test cases for checking values after reference change in a bean
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyReference.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/concept/types/property/ReferenceUpdateTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/test/AllTests.java
  de.dlr.sc.virsat.model.extension.tests/src-gen/de/dlr/sc/virsat/model/extension/tests/model/ATestCategoryBase.java
  de.dlr.sc.virsat.model.extension.tests/src-gen/de/dlr/sc/virsat/model/extension/tests/model/ATestCategoryReference.java
Labels: quality

#686 Generate code and fix errors in test cases - (Task #679)
  de.dlr.sc.virsat.model.concept/xtend-gen/de/dlr/sc/virsat/model/concept/generator/IGeneratorGapGenerator.java
  de.dlr.sc.virsat.model.ext.core.edit/src-dmf/de/dlr/sc/virsat/model/ext/core/core/provider/GenericCategoryItemProvider.java
  de.dlr.sc.virsat.model.extension.budget.power/src-gen/de/dlr/sc/virsat/model/extension/budget/power/model/APowerEquipment.java
  de.dlr.sc.virsat.model.extension.budget.power/src-gen/de/dlr/sc/virsat/model/extension/budget/power/model/APowerState.java
  de.dlr.sc.virsat.model.extension.funcelectrical/src-gen/de/dlr/sc/virsat/model/extension/funcelectrical/model/AInterface.java
  de.dlr.sc.virsat.model.extension.funcelectrical/src-gen/de/dlr/sc/virsat/model/extension/funcelectrical/model/AInterfaceEnd.java
  de.dlr.sc.virsat.model.extension.funcelectrical/src-gen/de/dlr/sc/virsat/model/extension/funcelectrical/model/APowerInterfaceType.java
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/AAttributeValue.java
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/AEnumerationDefinition.java
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ARequirement.java
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ARequirementAttribute.java
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ARequirementGroup.java
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ARequirementTrace.java
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ARequirementType.java
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ARequirementsConfiguration.java
  de.dlr.sc.virsat.model.extension.requirements/src-gen/de/dlr/sc/virsat/model/extension/requirements/model/ARequirementsSpecification.java
  de.dlr.sc.virsat.model.extension.statemachines/src-gen/de/dlr/sc/virsat/model/extension/statemachines/model/AAConstraint.java
  de.dlr.sc.virsat.model.extension.statemachines/src-gen/de/dlr/sc/virsat/model/extension/statemachines/model/AStateMachine.java
  de.dlr.sc.virsat.model.extension.statemachines/src-gen/de/dlr/sc/virsat/model/extension/statemachines/model/ATransition.java
  de.dlr.sc.virsat.model.extension.tests.edit.test/src/de/dlr/sc/virsat/project/resources/dmf/DmfResourceTest.java
  de.dlr.sc.virsat.model.extension.tests.edit/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/provider/EReferenceTestItemProvider.java
  de.dlr.sc.virsat.model.extension.tests.edit/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/provider/TestCategoryBeanAItemProvider.java
  de.dlr.sc.virsat.model.extension.tests.edit/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/provider/TestCategoryBeanAbstractItemProvider.java
  de.dlr.sc.virsat.model.extension.tests.edit/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/provider/TestCategoryBeanBItemProvider.java
  de.dlr.sc.virsat.model.extension.tests.edit/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/provider/TestCategoryBeanConcreteItemProvider.java
  de.dlr.sc.virsat.model.extension.tests.edit/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/provider/TestCategoryReferenceArrayItemProvider.java
  de.dlr.sc.virsat.model.extension.tests.edit/src-dmf/de/dlr/sc/virsat/model/extension/tests/tests/provider/TestCategoryReferenceItemProvider.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/concept/list/ArrayInstanceListIteratorTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyReferenceTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/dvlm/structural/command/DeleteStructuralElementInstanceCommandAcceptanceTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/model/TestCategoryIntrinsicArrayDynamicTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/model/TestCategoryIntrinsicArrayStaticTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/model/TestCategoryReferenceTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/project/editingDomain/commands/VirSatClipboardCommandAcceptanceTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/project/resources/dmf/DmfResourceTest.java
  de.dlr.sc.virsat.model.extension.tests/src-gen/de/dlr/sc/virsat/model/extension/tests/model/ATestCategoryBase.java
  de.dlr.sc.virsat.model.extension.tests/src-gen/de/dlr/sc/virsat/model/extension/tests/model/ATestCategoryComposition.java
  de.dlr.sc.virsat.model.extension.tests/src-gen/de/dlr/sc/virsat/model/extension/tests/model/ATestCategoryCompositionArray.java
  de.dlr.sc.virsat.model.extension.tests/src-gen/de/dlr/sc/virsat/model/extension/tests/model/ATestCategoryIntrinsicArray.java
  de.dlr.sc.virsat.model.extension.tests/src-gen/de/dlr/sc/virsat/model/extension/tests/model/ATestCategoryReference.java
  de.dlr.sc.virsat.model.extension.tests/src-gen/de/dlr/sc/virsat/model/extension/tests/model/ATestCategoryReferenceArray.java
  de.dlr.sc.virsat.model.extension.tests/src-gen/de/dlr/sc/virsat/model/extension/tests/model/ATestMassParameters.java
Labels: feature

#689 Exporting license package in jfreechart external lib plugin
  de.dlr.sc.virsat.external.lib.jfreechart/META-INF/MANIFEST.MF
Labels: build

#604 Add csv requirement import
  de.dlr.sc.virsat.external.lib.commons.csv/.checkstyle
  de.dlr.sc.virsat.external.lib.commons.csv/.classpath
  de.dlr.sc.virsat.external.lib.commons.csv/.project
  de.dlr.sc.virsat.external.lib.commons.csv/.settings/edu.umd.cs.findbugs.core.prefs
  de.dlr.sc.virsat.external.lib.commons.csv/.settings/org.eclipse.core.resources.prefs
  de.dlr.sc.virsat.external.lib.commons.csv/.settings/org.eclipse.core.runtime.prefs
  de.dlr.sc.virsat.external.lib.commons.csv/.settings/org.eclipse.jdt.core.prefs
  de.dlr.sc.virsat.external.lib.commons.csv/.settings/org.eclipse.m2e.core.prefs
  de.dlr.sc.virsat.external.lib.commons.csv/.settings/org.eclipse.mylyn.team.ui.prefs
  de.dlr.sc.virsat.external.lib.commons.csv/.settings/org.eclipse.pde.prefs
  de.dlr.sc.virsat.external.lib.commons.csv/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.external.lib.commons.csv/about.html
  de.dlr.sc.virsat.external.lib.commons.csv/about_files/LICENSE.txt
  de.dlr.sc.virsat.external.lib.commons.csv/about_files/NOTICE.txt
  de.dlr.sc.virsat.external.lib.commons.csv/about_files/THIRD-PARTY.txt
  de.dlr.sc.virsat.external.lib.commons.csv/build.properties
  de.dlr.sc.virsat.external.lib.commons.csv/externalLib/maven/commons-csv.jar
  de.dlr.sc.virsat.external.lib.commons.csv/pom.xml
  de.dlr.sc.virsat.external.lib.commons.csv/resources/.empty
  de.dlr.sc.virsat.external.lib.commons.csv/src/de/dlr/sc/virsat/external/lib/commons/csv/Activator.java
  de.dlr.sc.virsat.external.lib.feature/feature.xml
  de.dlr.sc.virsat.model.extension.requirements.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.requirements.test/src/de/dlr/sc/virsat/model/extension/requirements/csv/CsvFileReaderTest.java
  de.dlr.sc.virsat.model.extension.requirements.test/src/de/dlr/sc/virsat/model/extension/requirements/csv/RequirementsImporterTest.java
  de.dlr.sc.virsat.model.extension.requirements.test/src/de/dlr/sc/virsat/model/extension/requirements/test/AllTests.java
  de.dlr.sc.virsat.model.extension.requirements.test/src/de/dlr/sc/virsat/model/extension/requirements/util/RequirementHelperTest.java
  de.dlr.sc.virsat.model.extension.requirements.ui/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.requirements.ui/plugin.xml
  de.dlr.sc.virsat.model.extension.requirements.ui/src/de/dlr/sc/virsat/model/extension/requirements/ui/Activator.java
  de.dlr.sc.virsat.model.extension.requirements.ui/src/de/dlr/sc/virsat/model/extension/requirements/ui/wizard/CsvFileReqTypeSelectionPage.java
  de.dlr.sc.virsat.model.extension.requirements.ui/src/de/dlr/sc/virsat/model/extension/requirements/ui/wizard/CsvImportTargetSelectionPage.java
  de.dlr.sc.virsat.model.extension.requirements.ui/src/de/dlr/sc/virsat/model/extension/requirements/ui/wizard/CsvImportWizard.java
  de.dlr.sc.virsat.model.extension.requirements.ui/src/de/dlr/sc/virsat/model/extension/requirements/ui/wizard/CsvTypeReviewPage.java
  de.dlr.sc.virsat.model.extension.requirements/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.requirements/src/de/dlr/sc/virsat/model/extension/requirements/Activator.java
  de.dlr.sc.virsat.model.extension.requirements/src/de/dlr/sc/virsat/model/extension/requirements/csv/CsvFileReader.java
  de.dlr.sc.virsat.model.extension.requirements/src/de/dlr/sc/virsat/model/extension/requirements/csv/RequirementsImporter.java
  de.dlr.sc.virsat.model.extension.requirements/src/de/dlr/sc/virsat/model/extension/requirements/model/Requirement.java
  de.dlr.sc.virsat.model.extension.requirements/src/de/dlr/sc/virsat/model/extension/requirements/util/RequirementHelper.java
  de.dlr.sc.virsat.target/virsat.target
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/wizard/AImportExportPage.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/wizard/ATreeViewerPage.java
  pom.xml
Labels: feature

#682 SWTBot Test Cases for Role Management without Version Control Backend
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ASwtBotTestCase.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ProjectUiAllTests.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/RoleManagementTest.java
Labels: build, quality

#643 Added an SwtBot test for Apps - (Task #640)
  de.dlr.sc.virsat.model.concept/xtend-gen/de/dlr/sc/virsat/model/concept/generator/IGeneratorGapGenerator.java
  de.dlr.sc.virsat.swtbot.test/pom.xml
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ASwtBotTestCase.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/AppsTest.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/EditorTest.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ProjectUiAllTests.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ValidatorTest.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/GenericEditor.java
  launchers/SwtBot Tests.launch
Labels: quality

#692 Feature/task 684 enable filtering of available objects in reference selection dialog
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/contentProvider/AFilteredContentProvider.java
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/contentProvider/VirSatFilteredListContentProvider.java
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/contentProvider/VirSatFilteredWrappedTreeContentProvider.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/cellEditor/aproperties/ReferencePropertyCellEditingSupport.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/dialog/ReferenceSelectionDialog.java
Labels: comfort/usability, feature

#693 Trying to fix execution and test of apps
  de.dlr.sc.virsat.apps.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.apps.test/src/de/dlr/sc/virsat/apps/initializer/VirsatAppsInititalizerTest.java
  de.dlr.sc.virsat.apps/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.apps/src/de/dlr/sc/virsat/apps/initializer/VirsatAppsInitializer.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/AppsTest.java
Labels: bug, quality

#699 Corrected misspelled word - (Task #698)
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/general/UiSnippetBetaWarning.java
Labels: ui

#711 Git and SVN backends now properly resolve merge conflicts and dialogs show backend errors
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/versioningbackend/AVersioningBackendTest.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/versioningbackend/GitVersioningBackendTest.java
  de.dlr.sc.virsat.team.test/src/de/dlr/sc/virsat/team/AVirSatVersionControlBackendTest.java
  de.dlr.sc.virsat.team.test/src/de/dlr/sc/virsat/team/svn/VirSatSvnVersionControlBackendTest.java
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/handler/git/GitCommitHandler.java
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/handler/git/GitUpdateHandler.java
  de.dlr.sc.virsat.team/src/de/dlr/sc/virsat/team/git/VirSatGitVersionControlBackend.java
  de.dlr.sc.virsat.team/src/de/dlr/sc/virsat/team/svn/VirSatSvnVersionControlBackend.java
Labels: bug

#715 Fixing Incremental Builder on external runs - (Task #714)
  de.dlr.sc.virsat.build.test/src/de/dlr/sc/virsat/build/inheritance/VirSatInheritanceBuilderTest.java
  de.dlr.sc.virsat.build/src/de/dlr/sc/virsat/build/inheritance/AVirSatTransactionalBuilder.java
  de.dlr.sc.virsat.build/src/de/dlr/sc/virsat/build/inheritance/VirSatInheritanceBuilder.java
  de.dlr.sc.virsat.model.calculation/src/de/dlr/sc/virsat/model/calculation/compute/IncrementalEquationBuilder.java
Labels: bug
