Repository virtualsatellite/VirtualSatellite4-Core, pull requests merged in 2020-11, with the labels that each got.

#795 Fixed direct editing update behavior - (Task #337)
  de.dlr.sc.virsat.graphiti.test/src/de/dlr/sc/virsat/graphiti/util/DiagramHelperTest.java
  de.dlr.sc.virsat.graphiti.ui/src/de/dlr/sc/virsat/graphiti/ui/diagram/feature/BeanDirectEditNameFeature.java
  de.dlr.sc.virsat.graphiti.ui/src/de/dlr/sc/virsat/graphiti/ui/diagram/feature/BeanPropertyFloatDirectEditValueFeature.java
  de.dlr.sc.virsat.graphiti/src/de/dlr/sc/virsat/graphiti/util/DiagramHelper.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/StateMachineDiagramFeatureProvider.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/stateMachines/StateMachineUpdateFeature.java
Labels: bug

#803 Fixed abstract BeanProperty classes inconsistency
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/ABeanProperty.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/ABeanUnitValueProperty.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/ABeanValueProperty.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyBoolean.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyComposed.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyEReference.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyEnum.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyFloat.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyInt.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyReference.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyResource.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyString.java
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/contentProvider/VirSatTransactionalAdapterFactoryContentProvider.java
Labels: bug

#806 Added missing canExport check for calling exporters from the wizard
  de.dlr.sc.virsat.excel.test/src/de/dlr/sc/virsat/excel/ExcelExporterTest.java
  de.dlr.sc.virsat.excel.ui/src/de/dlr/sc/virsat/excel/ui/wizards/ExportWizard.java
  de.dlr.sc.virsat.excel/src/de/dlr/sc/virsat/excel/exporter/ExcelExporter.java
Labels: bug

#800 Deleted deprecated server classes and tests
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/dataaccess/TransactionalJsonProviderTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/dataaccess/VirSatGitAccessTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/AccessTestResourceTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/AuthTestResourceTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/ProjectManagementResourceTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/WorkspaceAccessResourceTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/WorkspaceUserContextTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/test/AJettyServerTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/test/AServerRepositoryTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/test/AllTests.java
  de.dlr.sc.virsat.server/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/dataaccess/Model.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/dataaccess/VirSatGitAccess.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/AccessTestResource.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/WorkspaceAccessResource.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/WorkspaceUserContext.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/servlet/VirSatModelAccessServlet.java
Labels: Server, quality

#817 Fix NPE when opening a graphiti diagram
  de.dlr.sc.virsat.graphiti.ui/src/de/dlr/sc/virsat/graphiti/ui/diagram/editor/VirSatDiagramBehavior.java
Labels: bug

#809 Improved creation of state machine diagrams
  de.dlr.sc.virsat.graphiti.ui/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.graphiti.ui/src/de/dlr/sc/virsat/graphiti/ui/handler/AOpenInDiagramEdiorHandler.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/plugin.xml
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/propertyTester/OpenStateMachineTester.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/editor/StateMachineDiagramEditor.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/handler/OpenStateMachineInDiagramEditorHandler.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/StateMachineDiagramTest.java
Labels: comfort/usability

#811 Introduced state layout feature - (Task #810)
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/StateMachineDiagramFeatureProvider.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/stateMachines/StateMachineAddFeature.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/stateMachines/StateMachineUpdateFeature.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/states/StateAddFeature.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/states/StateLayoutFeature.java
Labels: bug

#813 Removed PropertyResource
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/ModelAccessResourceTest.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/ModelAccessResource.java
Labels: Server, bug

#820 Improve look and feel of state machine diagrams
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/StateMachineDoubleClickFeature.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/stateMachines/StateMachineAddFeature.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/states/StateAddFeature.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/states/StateLayoutFeature.java
Labels: ui

#823 Add a "Clear" button for properties
  de.dlr.sc.virsat.model.extension.requirements.ui/src/de/dlr/sc/virsat/model/extension/requirements/ui/snippet/UiSnippetSectionRequirement.java
  de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/snippet/UiSnippetSectionVisualisation.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/AUiSnippetGenericPropertyInstances.java
Labels: bug, ui

#801 Added version number to existing REST APIs
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/AuthTestResourceTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/ModelAccessResourceTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/ProjectManagementResourceTest.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/jetty/VirSatJettyServer.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/servlet/RepoManagementServlet.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/servlet/VirSatModelAccessServlet.java
Labels: Server, feature

#837 Feature/task 832 add the cost icon
  de.dlr.sc.virsat.model.extension.budget.cost.ui/resources/icons/Interface.gif
  de.dlr.sc.virsat.model.extension.budget.cost.ui/resources/icons/InterfaceEnd.gif
  de.dlr.sc.virsat.model.extension.budget.cost.ui/resources/icons/InterfaceEnd_disabled.gif
  de.dlr.sc.virsat.model.extension.budget.cost.ui/resources/icons/Interface_disabled.gif
  de.dlr.sc.virsat.model.extension.budget.cost.ui/resources/icons/de.dlr.sc.virsat.model.extension.budget.cost.gif
  de.dlr.sc.virsat.model.extension.budget.cost.ui/resources/icons/de.dlr.sc.virsat.model.extension.budget.cost_disabled.gif
Labels: feature

#840 Prepared Github Actions based Continous Integration Workflow
  .github/workflows/main.yml
  .travis.yml
  README.md
  bash/deploy_sourceforge.sh
  bash/github_release.sh
  bash/maven_build.sh
  bash/setup.sh
  bash/setup_environment.sh
  build.xml
  de.dlr.sc.virsat.concept.unittest.util/src/de/dlr/sc/virsat/concept/unittest/util/test/AConceptTestCase.java
  de.dlr.sc.virsat.external.lib.apache.poi/pom.xml
  de.dlr.sc.virsat.external.lib.commons.cli/pom.xml
  de.dlr.sc.virsat.external.lib.commons.csv/pom.xml
  de.dlr.sc.virsat.external.lib.commons.math/pom.xml
  de.dlr.sc.virsat.external.lib.jersey/pom.xml
  de.dlr.sc.virsat.external.lib.jfreechart/pom.xml
  de.dlr.sc.virsat.external.lib.json-simple/pom.xml
  de.dlr.sc.virsat.external.lib.matlabfile/pom.xml
  id_ed25519.enc
  maven/pom.xml
Labels: build

#858 Improved build stability
  bash/maven_build.sh
Labels: build
