Repository virtualsatellite/VirtualSatellite4-Core, pull requests merged in 2020-03, with the labels that each got.

#496 Add default issue template - (Task #492)
  .github/ISSUE_TEMPLATE/default.md
Labels: comfort/usability

#517 Updated travis script for correct master builds
  .travis.yml
Labels: bug, build

#513 Add missing constructor in BeanProperties
  de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyBooleanTest.java
  de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyEReferenceTest.java
  de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyStringTest.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/ABeanObject.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/ABeanProperty.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyBoolean.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyEReference.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyString.java
Labels: quality

#515 Export to Matlab
  de.dlr.sc.virsat.external.lib.feature/feature.xml
  de.dlr.sc.virsat.external.lib.matlabfile/.classpath
  de.dlr.sc.virsat.external.lib.matlabfile/.project
  de.dlr.sc.virsat.external.lib.matlabfile/.settings/org.eclipse.core.resources.prefs
  de.dlr.sc.virsat.external.lib.matlabfile/.settings/org.eclipse.jdt.core.prefs
  de.dlr.sc.virsat.external.lib.matlabfile/.settings/org.eclipse.m2e.core.prefs
  de.dlr.sc.virsat.external.lib.matlabfile/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.external.lib.matlabfile/about.html
  de.dlr.sc.virsat.external.lib.matlabfile/about_files/LICENSE
  de.dlr.sc.virsat.external.lib.matlabfile/build.properties
  de.dlr.sc.virsat.external.lib.matlabfile/externalLib/mfl-core-0.5.6-javadoc.jar
  de.dlr.sc.virsat.external.lib.matlabfile/externalLib/mfl-core-0.5.6-sources.jar
  de.dlr.sc.virsat.external.lib.matlabfile/externalLib/mfl-core-0.5.6.jar
  de.dlr.sc.virsat.external.lib.matlabfile/pom.xml
  de.dlr.sc.virsat.external.lib.matlabfile/src/de/dlr/sc/virsat/external/lib/matlabfile/Activator.java
  de.dlr.sc.virsat.model.edit/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/dvlm/mat/MatExporter.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/dvlm/mat/MatHelper.java
  de.dlr.sc.virsat.model.extension.tests.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/dvlm/mat/MatExporterTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/test/AllTests.java
  pom.xml
Labels: feature

#527 Repair mat library import
  de.dlr.sc.virsat.model.feature/feature.xml
Labels: bug

#518 Migration with new dependencies
  de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/concept/migrator/AMigratorTest.java
  de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/concept/migrator/ConceptMigratorTest.java
  de.dlr.sc.virsat.model.edit/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/migrator/AMigrator.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/migrator/IMigrator.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/util/ConceptActivationHelper.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/dvlm/concepts/registry/ActiveConceptConfigurationElement.java
  de.dlr.sc.virsat.model.extension.tests.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/concept/util/ConceptActivationHelperTest.java
  de.dlr.sc.virsat.model.extension.tests/concept/concept.concept
  de.dlr.sc.virsat.model.extension.tests/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.tests/concept/concept_v1_0.xmi
  de.dlr.sc.virsat.model.extension.tests/concept/concept_v1_1.xmi
  de.dlr.sc.virsat.project.ui/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/migrator/handler/MigrateConceptToLatestHandler.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/general/UiSnippetActiveConcepts.java
Labels: bug, comfort/usability

#524 Return null if IntProperty is not set - (Task #523)
  de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyIntTest.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyInt.java
Labels: feature

#525 import from .mat-files
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/dvlm/mat/MatExporter.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/dvlm/mat/MatHelper.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/dvlm/mat/MatImporter.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/dvlm/mat/MatExporterTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/dvlm/mat/MatImporterTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/test/AllTests.java
  de.dlr.sc.virsat.model.external.tests/build.properties
  de.dlr.sc.virsat.model.external.tests/instance/InstanceModel.etests
  de.dlr.sc.virsat.model.external.tests/src/de/dlr/sc/virsat/model/external/tests/ExternalModelTestHelper.java
Labels: feature

#522 Add .empty files to VirSatProjectCommons folders - (Task #521)
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/structure/VirSatProjectCommonsTest.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/structure/VirSatProjectCommons.java
Labels: Server, easy, feature

#534 Adding virsat commons to model feature
  de.dlr.sc.virsat.model.feature/feature.xml
Labels: bug, build, concept IDE

#535 Feature/task 530 server configuration area
  de.dlr.sc.virsat.server.feature/feature.xml
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/configuration/ServerConfigurationTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/test/AllTests.java
  de.dlr.sc.virsat.server/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.server/build.properties
  de.dlr.sc.virsat.server/plugin.xml
  de.dlr.sc.virsat.server/resources/server.properties
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/Activator.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/VirSatServerApplication.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/configuration/ServerConfiguration.java
  de.dlr.sc.virsat.test/src/de/dlr/sc/virsat/test/ProjectAllTest.java
Labels: Server, feature

#538 Feature/task 519 refactor version cont
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/test/AProjectTestCase.java
  de.dlr.sc.virsat.team.feature/feature.xml
  de.dlr.sc.virsat.team.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.team.test/src/de/dlr/sc/virsat/team/git/VirSatGitVersionControlBackendTest.java
  de.dlr.sc.virsat.team.test/src/de/dlr/sc/virsat/team/test/AVirSatVersionControlBackendTest.java
  de.dlr.sc.virsat.team.test/src/de/dlr/sc/virsat/team/test/AllTests.java
  de.dlr.sc.virsat.team.test/src/de/dlr/sc/virsat/team/test/ExampleTest.java
  de.dlr.sc.virsat.team.ui/plugin.xml
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/action/git/GitCommitAction.java
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/action/git/GitCommitHandler.java
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/action/git/GitUpdateAction.java
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/action/git/GitUpdateHandler.java
  de.dlr.sc.virsat.team/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.team/src/de/dlr/sc/virsat/team/Activator.java
  de.dlr.sc.virsat.team/src/de/dlr/sc/virsat/team/IVirSatVersionControlBackend.java
  de.dlr.sc.virsat.team/src/de/dlr/sc/virsat/team/git/VirSatGitVersionControlBackend.java
  de.dlr.sc.virsat.test/src/de/dlr/sc/virsat/test/ProjectAllTest.java
  launchers/VirSat Core Application (other).launch
  launchers/VirSat Core Execute All Tests.launch
Labels: feature

#541 Feature/task 539 refactor svn backend
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/util/VirSatSelectionHelper.java
  de.dlr.sc.virsat.team.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.team.test/src/de/dlr/sc/virsat/team/svn/VirSatSvnVersionControlBackendTest.java
  de.dlr.sc.virsat.team.test/src/de/dlr/sc/virsat/team/test/AVirSatVersionControlBackendTest.java
  de.dlr.sc.virsat.team.test/src/de/dlr/sc/virsat/team/test/AllTests.java
  de.dlr.sc.virsat.team.ui/plugin.xml
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/action/git/GitCommitHandler.java
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/action/git/GitUpdateHandler.java
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/action/svn/SVNCommitAction.java
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/action/svn/SVNUpdateAction.java
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/handler/AVersionControlCommitHandler.java
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/handler/AVersionControlHandler.java
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/handler/AVersionControlUpdateHandler.java
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/handler/git/GitCommitHandler.java
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/handler/git/GitUpdateHandler.java
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/handler/svn/SvnCommitHandler.java
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/handler/svn/SvnUpdateHandler.java
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/util/VersionControlJob.java
  de.dlr.sc.virsat.team/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.team/src/de/dlr/sc/virsat/team/svn/VirSatSvnVersionControlBackend.java
  launchers/VirSat Core Execute All Tests.launch
Labels: feature

#543 Adapted check-in logic - (Task #542)
  de.dlr.sc.virsat.team.test/src/de/dlr/sc/virsat/team/test/AVirSatVersionControlBackendTest.java
  de.dlr.sc.virsat.team/src/de/dlr/sc/virsat/team/IVirSatVersionControlBackend.java
  de.dlr.sc.virsat.team/src/de/dlr/sc/virsat/team/git/VirSatGitVersionControlBackend.java
  de.dlr.sc.virsat.team/src/de/dlr/sc/virsat/team/svn/VirSatSvnVersionControlBackend.java
Labels: feature

#529 Renamed Import/Export/View categories- (Task #373)
  de.dlr.sc.virsat.excel.ui/plugin.xml
  de.dlr.sc.virsat.model.calculation.ui/plugin.xml
  de.dlr.sc.virsat.model.extension.funcelectrical.ui/plugin.xml
  de.dlr.sc.virsat.model.extension.mechanical.ui/plugin.xml
  de.dlr.sc.virsat.project.ui/plugin.xml
  de.dlr.sc.virsat.qudv.ui/plugin.xml
Labels: easy, ui

#544 Persistence Layer for Rest API server
  de.dlr.sc.virsat.commons.test/src/de/dlr/sc/virsat/commons/exception/AtomicExceptionTest.java
  de.dlr.sc.virsat.commons.test/src/de/dlr/sc/virsat/commons/test/AllTests.java
  de.dlr.sc.virsat.commons/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.commons/src/de/dlr/sc/virsat/commons/exception/AtomicException.java
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/wizard/VirSatProjectWizard.java
  de.dlr.sc.virsat.project/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/structure/VirSatProjectCommons.java
  de.dlr.sc.virsat.server.test/.gitignore
  de.dlr.sc.virsat.server.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/configuration/RepositoryConfigurationTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/configuration/ServerConfigurationTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/repository/RepoRegistryTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/repository/ServerRepoHelperTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/repository/ServerRepositoryTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/test/AllTests.java
  de.dlr.sc.virsat.server/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.server/resources/server.properties
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/VirSatServerApplication.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/configuration/RepositoryConfiguration.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/configuration/ServerConfiguration.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/repository/RepoRegistry.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/repository/ServerRepoHelper.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/repository/ServerRepository.java
  de.dlr.sc.virsat.target/tmodel-src/virsat.tmodel
  de.dlr.sc.virsat.target/virsat.target
  de.dlr.sc.virsat.team.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.team.test/src/de/dlr/sc/virsat/team/AVirSatVersionControlBackendTest.java
  de.dlr.sc.virsat.team.test/src/de/dlr/sc/virsat/team/VersionControlBackendProviderTest.java
  de.dlr.sc.virsat.team.test/src/de/dlr/sc/virsat/team/git/VirSatGitVersionControlBackendTest.java
  de.dlr.sc.virsat.team.test/src/de/dlr/sc/virsat/team/svn/VirSatSvnVersionControlBackendTest.java
  de.dlr.sc.virsat.team.test/src/de/dlr/sc/virsat/team/test/AllTests.java
  de.dlr.sc.virsat.team.test/src/de/dlr/sc/virsat/team/test/CreateSvnServerOperation.java
  de.dlr.sc.virsat.team/src/de/dlr/sc/virsat/team/IVirSatVersionControlBackend.java
  de.dlr.sc.virsat.team/src/de/dlr/sc/virsat/team/VersionControlBackendProvider.java
  de.dlr.sc.virsat.team/src/de/dlr/sc/virsat/team/VersionControlSystem.java
  de.dlr.sc.virsat.team/src/de/dlr/sc/virsat/team/git/VirSatGitVersionControlBackend.java
  de.dlr.sc.virsat.team/src/de/dlr/sc/virsat/team/svn/VirSatSvnVersionControlBackend.java
Labels: Server, feature
