Repository virtualsatellite/VirtualSatellite4-Core, pull requests merged in 2020-02, with the labels that each got.

#433 Improve coding style in excel-Plugins
  de.dlr.sc.virsat.excel.test/src/de/dlr/sc/virsat/excel/ExcelExporterTest.java
  de.dlr.sc.virsat.excel.test/src/de/dlr/sc/virsat/excel/ExcelImporterTest.java
  de.dlr.sc.virsat.excel.test/src/de/dlr/sc/virsat/excel/FaultTest.java
  de.dlr.sc.virsat.excel.test/src/de/dlr/sc/virsat/excel/commands/ImportCommandTest.java
  de.dlr.sc.virsat.excel.test/src/de/dlr/sc/virsat/excel/test/AllTests.java
  de.dlr.sc.virsat.excel.test/src/de/dlr/sc/virsat/excel/test/ExcelTestActivator.java
  de.dlr.sc.virsat.excel.ui/src/de/dlr/sc/virsat/excel/ui/Activator.java
  de.dlr.sc.virsat.excel.ui/src/de/dlr/sc/virsat/excel/ui/wizards/ExportPage.java
  de.dlr.sc.virsat.excel.ui/src/de/dlr/sc/virsat/excel/ui/wizards/ExportWizard.java
  de.dlr.sc.virsat.excel.ui/src/de/dlr/sc/virsat/excel/ui/wizards/ImportPage.java
  de.dlr.sc.virsat.excel.ui/src/de/dlr/sc/virsat/excel/ui/wizards/ImportWizard.java
  de.dlr.sc.virsat.excel/src/de/dlr/sc/virsat/excel/AExcelIo.java
  de.dlr.sc.virsat.excel/src/de/dlr/sc/virsat/excel/Activator.java
  de.dlr.sc.virsat.excel/src/de/dlr/sc/virsat/excel/commands/ImportCommand.java
  de.dlr.sc.virsat.excel/src/de/dlr/sc/virsat/excel/exporter/ExcelExportHelper.java
  de.dlr.sc.virsat.excel/src/de/dlr/sc/virsat/excel/exporter/ExcelExporter.java
  de.dlr.sc.virsat.excel/src/de/dlr/sc/virsat/excel/exporter/IExport.java
  de.dlr.sc.virsat.excel/src/de/dlr/sc/virsat/excel/fault/Fault.java
  de.dlr.sc.virsat.excel/src/de/dlr/sc/virsat/excel/fault/FaultType.java
  de.dlr.sc.virsat.excel/src/de/dlr/sc/virsat/excel/importer/ExcelImportHelper.java
  de.dlr.sc.virsat.excel/src/de/dlr/sc/virsat/excel/importer/ExcelImporter.java
  de.dlr.sc.virsat.excel/src/de/dlr/sc/virsat/excel/importer/IImport.java
  de.dlr.sc.virsat.model.extension.funcelectrical.test/src/de/dlr/sc/virsat/model/extension/funcelectrical/excel/exporter/FuncElecExporterTest.java
  de.dlr.sc.virsat.model.extension.funcelectrical.test/src/de/dlr/sc/virsat/model/extension/funcelectrical/excel/importer/FuncElecImporterTest.java
  de.dlr.sc.virsat.model.extension.funcelectrical.test/src/de/dlr/sc/virsat/model/extension/funcelectrical/excel/importer/ImportValidatorTest.java
  de.dlr.sc.virsat.model.extension.funcelectrical.test/src/de/dlr/sc/virsat/model/extension/funcelectrical/test/ExcelTestCase.java
  de.dlr.sc.virsat.model.extension.funcelectrical/src/de/dlr/sc/virsat/model/extension/funcelectrical/excel/exporter/FuncElecExporter.java
  de.dlr.sc.virsat.model.extension.funcelectrical/src/de/dlr/sc/virsat/model/extension/funcelectrical/excel/importer/FuncElecImporter.java
  de.dlr.sc.virsat.model.extension.funcelectrical/src/de/dlr/sc/virsat/model/extension/funcelectrical/excel/importer/ImportValidator.java
  de.dlr.sc.virsat.model.extension.statemachines.test/src/de/dlr/sc/virsat/model/extension/statemachines/excel/exporter/ExcelExporterTest.java
  de.dlr.sc.virsat.model.extension.statemachines.test/src/de/dlr/sc/virsat/model/extension/statemachines/excel/importer/ExcelImporterTest.java
  de.dlr.sc.virsat.model.extension.statemachines/src/de/dlr/sc/virsat/model/extension/statemachines/excel/exporter/StateMachineExporter.java
  de.dlr.sc.virsat.model.extension.statemachines/src/de/dlr/sc/virsat/model/extension/statemachines/excel/importer/ImportValidator.java
  de.dlr.sc.virsat.model.extension.statemachines/src/de/dlr/sc/virsat/model/extension/statemachines/excel/importer/SMImporter.java
Labels: quality

#458 Improve deployment process
  .mailmap
  .travis.yml
  bash/deploy_sourceforge.sh
  bash/ssh-add-password.sh
  bash/verify_commit_authors.sh
  id_ed25519.enc
Labels: build

#364 Providing Equinox based REST Server and product deployment
  de.dlr.sc.virsat.external.lib.jersey/pom.xml
  de.dlr.sc.virsat.external.lib.jersey/src/de/dlr/virsat/external/lib/jersey/Activator.java
  de.dlr.sc.virsat.external.lib.jersey/src/de/dlr/virsat/external/lib/jersey/servlet/ApplicationServletContainer.java
  de.dlr.sc.virsat.model.extension.funcelectrical.ui/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.product/pom.xml
  de.dlr.sc.virsat.product/virsat_server.p2.inf
  de.dlr.sc.virsat.product/virsat_server.product
  de.dlr.sc.virsat.server.feature/feature.xml
  de.dlr.sc.virsat.server.test/pom.xml
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/data/VirSatGitAccessTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/dataaccess/VirSatGitAccessTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/WorkspaceAccessResourceTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/WorkspaceUserContextTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/test/AGitAndJettyServerTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/test/AllTests.java
  de.dlr.sc.virsat.server/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.server/build.properties
  de.dlr.sc.virsat.server/plugin.xml
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/VirSatServerApplication.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/data/VirSatGitAccess.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/dataaccess/Model.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/dataaccess/VirSatGitAccess.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/jetty/VirSatJettyServer.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/AccessTestResource.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/ModelAccessResource.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/WorkspaceAccessResource.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/WorkspaceUserContext.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/servlet/VirSatModelAccessServlet.java
  launchers/Launch Runtime Eclipse.launch
  launchers/VirSat Headless Server.launch
  maven/pom.xml
Labels: Server, build, feature

#468 SWTBot Fix 1: Setting up SwtBot Recorder for VirSat Core
  de.dlr.sc.virsat.target/tmodel-src/virsat.tmodel
  de.dlr.sc.virsat.target/virsat.target
  launchers/VirSat Core Application (SwtBot).launch
Labels: build, easy, feature

#473 Fixed build script for correct processing order of jacoco and codecov
  .travis.yml
  bash/maven_build.sh
Labels: bug, build, easy

#470 SWTBot Fix 3: Improved Workspace Synchronization
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/wizard/VirSatProjectWizard.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/editingDomain/VirSatSaveJob.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/editingDomain/VirSatTransactionalEditingDomain.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/editingDomain/VirSatWorkspaceCommandStack.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/GenericEditor.java
Labels: bug, build, quality

#469 SWTBot Fix 2: Refactored Builders and improve Logging
  de.dlr.sc.virsat.build/src/de/dlr/sc/virsat/build/inheritance/AVirSatBuilder.java
  de.dlr.sc.virsat.build/src/de/dlr/sc/virsat/build/inheritance/AVirSatTransactionalBuilder.java
  de.dlr.sc.virsat.build/src/de/dlr/sc/virsat/build/inheritance/VirSatInheritanceBuilder.java
  de.dlr.sc.virsat.build/src/de/dlr/sc/virsat/build/validator/VirSatValidatorBuilder.java
  de.dlr.sc.virsat.model.calculation/src/de/dlr/sc/virsat/model/calculation/compute/IncrementalEquationBuilder.java
Labels: bug, build, quality

#471 SWTBot Fix 4: Improved logging for SWTBotTests
  de.dlr.sc.virsat.branding.ui/plugin_customization.ini
  de.dlr.sc.virsat.swtbot.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ASwtBotTestCase.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/Activator.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/CalculationTest.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/CutCopyDeleteUndoTest.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/EditorTest.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/InheritanceTest.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/NewProjectWizardTest.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ProductStructureTest.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ProjectUiAllTests.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/util/SwtBotDebugHelper.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/util/SwtBotSection.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/util/SwtThreadWatcher.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/util/VirSatWaitForProjectBuilder.java
Labels: bug, build, quality

#476 remove dead variables
  de.dlr.sc.virsat.excel.test/src/de/dlr/sc/virsat/excel/test/ExcelTestActivator.java
  de.dlr.sc.virsat.excel.ui/src/de/dlr/sc/virsat/excel/ui/wizards/ImportWizard.java
  de.dlr.sc.virsat.model.extension.funcelectrical.test/src/de/dlr/sc/virsat/model/extension/funcelectrical/test/ExcelTestCase.java
  de.dlr.sc.virsat.model.extension.funcelectrical.test/src/de/dlr/sc/virsat/model/extension/funcelectrical/test/TestActivator.java
  de.dlr.sc.virsat.model.extension.funcelectrical/src/de/dlr/sc/virsat/model/extension/funcelectrical/Activator.java
  de.dlr.sc.virsat.model.extension.funcelectrical/src/de/dlr/sc/virsat/model/extension/funcelectrical/excel/exporter/FuncElecExporter.java
  de.dlr.sc.virsat.model.extension.statemachines.test/src/de/dlr/sc/virsat/model/extension/statemachines/excel/exporter/ExcelExporterTest.java
  de.dlr.sc.virsat.model.extension.statemachines.test/src/de/dlr/sc/virsat/model/extension/statemachines/excel/importer/ExcelImporterTest.java
  de.dlr.sc.virsat.model.extension.statemachines/src/de/dlr/sc/virsat/model/extension/statemachines/Activator.java
  de.dlr.sc.virsat.model.extension.statemachines/src/de/dlr/sc/virsat/model/extension/statemachines/excel/exporter/StateMachineExporter.java
Labels: quality

#482 Moved registration of command line arguments
  de.dlr.sc.virsat.external.lib.commons.cli/plugin.xml
  de.dlr.sc.virsat.model/plugin.xml
  de.dlr.sc.virsat.uiengine.ui/plugin.xml
Labels: quality

#475 Fixed TableNavigation and Selection
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ASwtBotTestCase.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/InheritanceTest.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/cellEditor/aproperties/ReferencePropertyCellEditingSupport.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/cellEditor/aproperties/ResourcePropertyCellEditingSupport.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/AUiSnippetGenericTable.java
Labels: bug

#488 Added test plugins to test feature - (Task #487)
  de.dlr.sc.virsat.test.feature/feature.xml
  de.dlr.sc.virsat.test/META-INF/MANIFEST.MF
Labels: build

#479 Threading: Change Editing domain to lock workspace on tryRunExclsuive
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/editingDomain/VirSatTransactionalEditingDomainTest.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/editingDomain/VirSatTransactionalEditingDomain.java
Labels: bug

#484 Add git to user manual - (Task #483)
  de.dlr.sc.virsat.docs.feature/src/docs/VirSat_Core_User_Manual.adoc
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterSettingUpInfrastructure/Workflow.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterSettingUpInfrastructure/Workflow.pptx
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterSettingUpInfrastructure/add-repository.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterSettingUpInfrastructure/branches.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterSettingUpInfrastructure/clone-repository.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterSettingUpInfrastructure/clone-select-location.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterSettingUpInfrastructure/git-commit.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterSettingUpInfrastructure/git-perspective.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterSettingUpInfrastructure/import-projects.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterSettingUpInfrastructure/select-import.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterSettingUpInfrastructure/select-repository.png
  de.dlr.sc.virsat.docs.feature/src/docs/images/chapterSettingUpInfrastructure/share-git.png
Labels: quality

#494 Only create editor snippet extension if needed
  de.dlr.sc.virsat.model.concept/src/de/dlr/sc/virsat/model/concept/generator/plugin/GenerateUiPluginXml.xtend
  de.dlr.sc.virsat.model.concept/xtend-gen/de/dlr/sc/virsat/model/concept/generator/plugin/GenerateUiPluginXml.java
Labels: concept IDE, quality

#500 Fix for Workspace Sychronisation - (Task #499)
  de.dlr.sc.virsat.graphiti.ui/src/de/dlr/sc/virsat/graphiti/ui/diagram/editor/VirSatDiagramUpdateBehavior.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/editingDomain/VirSatTransactionalEditingDomain.java
Labels: bug
