Repository virtualsatellite/VirtualSatellite4-Core, pull requests merged in 2020-09, with the labels that each got.

#696 Expand navigator to target when drag & drop - (Task #31)
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/VirSatNavigator.java
Labels: comfort/usability, ui

#731 Added new units and quantity kinds for thermal domain - (Task #729)
  de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/dvlm/qudv/util/QudvUnitHelperTest.java
  de.dlr.sc.virsat.model/src/de/dlr/sc/virsat/model/dvlm/qudv/util/QudvUnitHelper.java
Labels: feature

#732 Added check for int type in setter - (Task #700)
  de.dlr.sc.virsat.model.calculation.test/src/de/dlr/sc/virsat/model/calculation/compute/EquationHelperTest.java
  de.dlr.sc.virsat.model.calculation.test/src/de/dlr/sc/virsat/model/calculation/compute/NumberLiteralSetterTest.java
  de.dlr.sc.virsat.model.calculation/src/de/dlr/sc/virsat/model/calculation/compute/extensions/NumberLiteralSetter.java
Labels: bug

#730 Improve RepoManagementController
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/controller/RepoManagementControllerTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/repository/ServerRepoHelperTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/repository/ServerRepositoryTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/ProjectManagementResourceTest.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/controller/RepoManagementController.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/repository/ServerRepoHelper.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/repository/ServerRepository.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/ProjectManagementResource.java
Labels: Server, feature

#736 Added missing default constructor in ExcelExporter Classes - (Task #735)
  de.dlr.sc.virsat.model.extension.funcelectrical/src/de/dlr/sc/virsat/model/extension/funcelectrical/excel/exporter/FuncElecExporter.java
  de.dlr.sc.virsat.model.extension.statemachines/src/de/dlr/sc/virsat/model/extension/statemachines/excel/exporter/StateMachineExporter.java
Labels: bug

#738 Refactored excel exporter constants - (Task #737)
  de.dlr.sc.virsat.excel/src/de/dlr/sc/virsat/excel/AExcelIo.java
  de.dlr.sc.virsat.excel/src/de/dlr/sc/virsat/excel/exporter/ExcelExportHelper.java
  de.dlr.sc.virsat.model.extension.funcelectrical/src/de/dlr/sc/virsat/model/extension/funcelectrical/excel/AExcelFuncIO.java
  de.dlr.sc.virsat.model.extension.funcelectrical/src/de/dlr/sc/virsat/model/extension/funcelectrical/excel/importer/ImportValidator.java
  de.dlr.sc.virsat.model.extension.statemachines/src/de/dlr/sc/virsat/model/extension/statemachines/excel/exporter/StateMachineExporter.java
  de.dlr.sc.virsat.model.extension.statemachines/src/de/dlr/sc/virsat/model/extension/statemachines/excel/importer/ImportValidator.java
Labels: quality

#740 Added InterfacEnd FQN column to excel export - (Task #739)
  de.dlr.sc.virsat.model.extension.funcelectrical.test/resources/SampleTest.xlsx
  de.dlr.sc.virsat.model.extension.funcelectrical.test/src/de/dlr/sc/virsat/model/extension/funcelectrical/excel/exporter/FuncElecExporterTest.java
  de.dlr.sc.virsat.model.extension.funcelectrical/resources/ExcelExportTemplate.xlsx
  de.dlr.sc.virsat.model.extension.funcelectrical/src/de/dlr/sc/virsat/model/extension/funcelectrical/excel/AExcelFuncIO.java
  de.dlr.sc.virsat.model.extension.funcelectrical/src/de/dlr/sc/virsat/model/extension/funcelectrical/excel/exporter/FuncElecExporter.java
Labels: comfort/usability, feature
