Repository virtualsatellite/VirtualSatellite4-Core, pull requests merged in 2020-04, with the labels that each got.

#546 Improved Temporary Test Resource Clean Up
  de.dlr.sc.virsat.commons/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.commons/src/de/dlr/sc/virsat/commons/Activator.java
  de.dlr.sc.virsat.commons/src/de/dlr/sc/virsat/commons/file/VirSatFileUtils.java
  de.dlr.sc.virsat.model.extension.mechanical.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/cad/CadFileHandlerTest.java
  de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/cad/CadImporterTest.java
  de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/cad/command/CopyResourceCommandTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/editingDomain/VirSatTransactionalEditingDomainTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/test/AProjectTestCase.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/configuration/RepositoryConfigurationTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/configuration/ServerConfigurationTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/repository/ServerRepoHelperTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/repository/ServerRepositoryTest.java
  de.dlr.sc.virsat.team.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.team.test/src/de/dlr/sc/virsat/team/AVirSatVersionControlBackendTest.java
  de.dlr.sc.virsat.team.test/src/de/dlr/sc/virsat/team/VersionControlBackendProviderTest.java
  de.dlr.sc.virsat.team.test/src/de/dlr/sc/virsat/team/git/VirSatGitVersionControlBackendTest.java
  de.dlr.sc.virsat.team.test/src/de/dlr/sc/virsat/team/svn/VirSatSvnVersionControlBackendTest.java
  de.dlr.sc.virsat.team/src/de/dlr/sc/virsat/team/git/VirSatGitVersionControlBackend.java
Labels: quality

#552 Fix shaky code coverage
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/structure/VirSatProjectCommonsTest.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/structure/VirSatProjectCommons.java
Labels: easy, quality

#514 Fix performance issue
  de.dlr.sc.virsat.model.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/ecore/VirSatEcoreUtilTest.java
  de.dlr.sc.virsat.model/src/de/dlr/sc/virsat/model/ecore/VirSatEcoreUtil.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/resources/VirSatResourceSetTest.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/resources/VirSatResourceSet.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/GenericEditor.java
Labels: quality

#557 Exporting de.dlr.sc.virsat.project.ui.wizard - (Task #553)
  de.dlr.sc.virsat.project.ui/META-INF/MANIFEST.MF
Labels: easy, quality

#550 Feature/task 540 rest endpoint for repo management
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/configuration/RepositoryConfigurationTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/controller/RepoManagementControllerTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/repository/RepoRegistryTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/repository/ServerRepoHelperTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/ProjectManagementResourceTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/test/AGitAndJettyServerTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/test/AllTests.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/configuration/RepositoryConfiguration.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/controller/RepoManagementController.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/jetty/VirSatJettyServer.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/ProjectManagementResource.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/servlet/RepoManagementServlet.java
Labels: Server, feature

#560 Updated License informations
  NOTICE.md
  de.dlr.sc.virsat.branding.ui/about.html
  de.dlr.sc.virsat.branding.ui/plugin.xml
  de.dlr.sc.virsat.docs.feature/docs/NOTICE.md
  de.dlr.sc.virsat.product/virsat_core.product
Labels: bug, quality, release

#480 Graphiti methods pull up to VirSat Core - (Task #477)
  de.dlr.sc.virsat.swtbot.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ASwtBotTestCase.java
Labels: quality

#558 Fixed inconsistent vendor names - (Task #474)
  de.dlr.sc.virsat.model.edit.test/plugin.properties
  de.dlr.sc.virsat.model.edit/plugin.properties
  de.dlr.sc.virsat.model.external.tests.edit/plugin.properties
  de.dlr.sc.virsat.model.external.tests/plugin.properties
  de.dlr.sc.virsat.model.test/plugin.properties
  de.dlr.sc.virsat.model/plugin.properties
  de.dlr.sc.virsat.uiengine.ui/plugin.properties
Labels: quality

#565 Fixing closing welcome screen - (Task #564)
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ASwtBotTestCase.java
Labels: quality

#574 Added a getter for wrapped cp - (Task #573)
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/contentProvider/VirSatFilteredWrappedTreeContentProvider.java
Labels: feature

#575 Added test cases for safeGetResource - (Task #572)
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/resources/VirSatResourceSetTest.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/resources/VirSatResourceSet.java
Labels: build, easy, quality

#578 Improve Test Case for Git Backend
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/test/AProjectTestCase.java
  de.dlr.sc.virsat.team.test/src/de/dlr/sc/virsat/team/AVirSatVersionControlBackendTest.java
  de.dlr.sc.virsat.team.test/src/de/dlr/sc/virsat/team/git/VirSatGitVersionControlBackendTest.java
Labels: bug, quality

#586 Create DVLM Release
  de.dlr.sc.virsat.model.calculation/src-gen/de/dlr/sc/virsat/model/calculation/EquationDSL.xtextbin
  de.dlr.sc.virsat.model.calculation/src-gen/de/dlr/sc/virsat/model/calculation/validation/AbstractEquationDSLValidator.java
  de.dlr.sc.virsat.model.calculation/src/de/dlr/sc/virsat/model/calculation/EquationDSL.xtext
  de.dlr.sc.virsat.model.concept/src-gen/de/dlr/sc/virsat/model/concept/ConceptLanguage.xtextbin
  de.dlr.sc.virsat.model.concept/src-gen/de/dlr/sc/virsat/model/concept/validation/AbstractConceptLanguageValidator.java
  de.dlr.sc.virsat.model.concept/src/de/dlr/sc/virsat/model/concept/ConceptLanguage.xtext
  de.dlr.sc.virsat.model.edit/plugin.xml
  de.dlr.sc.virsat.model.ext.core/concept/concept.xmi
  de.dlr.sc.virsat.model.ext.core/concept/concept_v1_0.xmi
  de.dlr.sc.virsat.model.extension.budget.mass/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.budget.mass/concept/concept_v1_1.xmi
  de.dlr.sc.virsat.model.extension.budget.power/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.budget.power/concept/concept_v1_0.xmi
  de.dlr.sc.virsat.model.extension.funcelectrical/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.funcelectrical/concept/concept_v2_0.xmi
  de.dlr.sc.virsat.model.extension.maturity/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.maturity/concept/concept_v1_1.xmi
  de.dlr.sc.virsat.model.extension.mechanical/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.mechanical/concept/concept_v0_1.xmi
  de.dlr.sc.virsat.model.extension.ps/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.ps/concept/concept_v1_2.xmi
  de.dlr.sc.virsat.model.extension.requirements/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.requirements/concept/concept_v0_1.xmi
  de.dlr.sc.virsat.model.extension.statemachines/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.statemachines/concept/concept_v1_1.xmi
  de.dlr.sc.virsat.model.extension.tests/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.tests/concept/concept_v1_1.xmi
  de.dlr.sc.virsat.model.extension.visualisation/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.visualisation/concept/concept_v1_3.xmi
  de.dlr.sc.virsat.model/model/dvlm.ecore
  de.dlr.sc.virsat.model/model/dvlm.history
  de.dlr.sc.virsat.model/plugin.xml
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/DVLMPackage.java
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/calculation/CalculationPackage.java
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/categories/CategoriesPackage.java
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/categories/propertydefinitions/PropertydefinitionsPackage.java
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/categories/propertyinstances/PropertyinstancesPackage.java
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/concepts/ConceptsPackage.java
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/dmf/DmfPackage.java
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/general/GeneralPackage.java
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/inheritance/InheritancePackage.java
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/qudv/QudvPackage.java
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/roles/RolesPackage.java
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/structural/StructuralPackage.java
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/types/TypesPackage.java
  de.dlr.sc.virsat.model/src-gen/de/dlr/sc/virsat/model/dvlm/units/UnitsPackage.java
Labels: build

#576 PR #2 for User Context Implementation - Rights Helper Interface
  de.dlr.sc.virsat.apps/src/de/dlr/sc/virsat/apps/api/external/ModelAPI.java
  de.dlr.sc.virsat.graphiti/src/de/dlr/sc/virsat/graphiti/util/DiagramHelper.java
  de.dlr.sc.virsat.model.calculation/src/de/dlr/sc/virsat/model/calculation/compute/EquationHelper.java
  de.dlr.sc.virsat.model.extension.funcelectrical.ui/src/de/dlr/sc/virsat/model/extension/funcelectrical/ui/diagram/features/interfacetypes/InterfaceTypeAddFeature.java
  de.dlr.sc.virsat.model.extension.ps.ui/src/de/dlr/sc/virsat/model/extension/ps/ui/handler/ConfigureHandler.java
  de.dlr.sc.virsat.model.extension.ps.ui/src/de/dlr/sc/virsat/model/extension/ps/ui/handler/GenerateHandler.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/handler/ConstraintTableHandler.java
  de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/dvlm/roles/RightsHelperTest.java
  de.dlr.sc.virsat.model/src/de/dlr/sc/virsat/model/dvlm/inheritance/InheritanceCopier.java
  de.dlr.sc.virsat.model/src/de/dlr/sc/virsat/model/dvlm/roles/IRightsHelper.java
  de.dlr.sc.virsat.model/src/de/dlr/sc/virsat/model/dvlm/roles/RightsHelper.java
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/propertyTester/WritePermissionTester.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/resources/VirSatResourceSet.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/GenericEditor.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/AUiSectionSnippet.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/AUiSnippetGenericPropertyInstances.java
Labels: Server, feature

#508 Add HTTP authentication and authorization to REST server (#454)
  de.dlr.sc.virsat.server.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.server.test/resources/test_users.properties
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/auth/LoginServiceFactoryTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/configuration/ServerConfigurationTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/AccessTestResourceTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/AuthTestResourceTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/resources/WorkspaceAccessResourceTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/test/AGitAndJettyServerTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/test/AllTests.java
  de.dlr.sc.virsat.server/resources/auth.properties
  de.dlr.sc.virsat.server/resources/server.properties
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/Activator.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/VirSatServerApplication.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/auth/LoginServiceFactory.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/auth/ServerRoles.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/auth/filter/DynamicRepositoryFilterBinding.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/auth/filter/RepositoryFilter.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/configuration/ServerConfiguration.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/jetty/VirSatJettyServer.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/AuthTestResource.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/servlet/VirSatModelAccessServlet.java
Labels: Server

#583 Fixing shaky test cases - Adding Test Cases for Excel Exporter Helper
  de.dlr.sc.virsat.excel.test/src/de/dlr/sc/virsat/excel/exporter/ExcelExportHelperTest.java
  de.dlr.sc.virsat.excel.test/src/de/dlr/sc/virsat/excel/test/AllTests.java
  de.dlr.sc.virsat.excel/src/de/dlr/sc/virsat/excel/exporter/ExcelExportHelper.java
  de.dlr.sc.virsat.model.extension.funcelectrical.test/src/de/dlr/sc/virsat/model/extension/funcelectrical/excel/exporter/FuncElecExporterTest.java
  de.dlr.sc.virsat.model.extension.funcelectrical/src/de/dlr/sc/virsat/model/extension/funcelectrical/excel/exporter/FuncElecExporter.java
  de.dlr.sc.virsat.model.extension.statemachines.test/src/de/dlr/sc/virsat/model/extension/statemachines/excel/exporter/ExcelExporterTest.java
  de.dlr.sc.virsat.model.extension.statemachines/src/de/dlr/sc/virsat/model/extension/statemachines/excel/exporter/StateMachineExporter.java
Labels: bug, quality

#585 Refactor SEI delete functionality for server
  de.dlr.sc.virsat.graphiti.ui/src/de/dlr/sc/virsat/graphiti/ui/diagram/feature/BeanDeleteFeature.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/dvlm/structural/command/DeleteStructuralElementInstanceCommand.java
  de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/dvlm/structural/util/StructuralElementInstanceHelperTest.java
  de.dlr.sc.virsat.model/src/de/dlr/sc/virsat/model/dvlm/structural/util/StructuralElementInstanceHelper.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/structure/command/CreateRemoveSeiWithFileStructureCommandTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/structure/command/RemoveFileStructureCommandTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/structure/operation/NoUndoDeleteResourceOperationTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/test/AllTests.java
  de.dlr.sc.virsat.project.ui/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/handler/DeleteStructuralElementInstanceHandler.java
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/propertyTester/RemoveStructuralElementInstanceTester.java
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/structure/command/RemoveFileStructureCommand.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/structure/command/CreateRemoveSeiWithFileStructureCommand.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/structure/command/RemoveFileStructureCommand.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/structure/operation/NoUndoDeleteResourceOperation.java
Labels: Server, feature
