Repository virtualsatellite/VirtualSatellite4-Core, pull requests merged in 2020-01, with the labels that each got.

#407 Trying to fix shakey coverage test cases
  bash/deploy_sourceforge.sh
  de.dlr.sc.virsat.build.test/src/de/dlr/sc/virsat/build/inheritance/VirSatInheritanceBuilderTest.java
  de.dlr.sc.virsat.build.test/src/de/dlr/sc/virsat/build/validator/VirSatValidatorBuilderTest.java
  de.dlr.sc.virsat.build/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.build/src/de/dlr/sc/virsat/build/inheritance/AVirSatBuilder.java
  de.dlr.sc.virsat.build/src/de/dlr/sc/virsat/build/inheritance/AVirSatTransactionalBuilder.java
  de.dlr.sc.virsat.build/src/de/dlr/sc/virsat/build/inheritance/VirSatInheritanceBuilder.java
  de.dlr.sc.virsat.build/src/de/dlr/sc/virsat/build/validator/VirSatValidatorBuilder.java
  de.dlr.sc.virsat.concept.unittest.util/src/de/dlr/sc/virsat/concept/unittest/util/test/AConceptTestCase.java
  de.dlr.sc.virsat.model.calculation/src/de/dlr/sc/virsat/model/calculation/compute/IncrementalEquationBuilder.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/dvlm/util/command/VirSatRecordingCommand.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/editingDomain/VirSatTransactionalEditingDomainTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/editingDomain/VirSatWorkspaceCommandStackTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/resources/VirSatResourceSetTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/test/AProjectTestCase.java
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/VirSatNavigator.java
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/wizard/VirSatProjectWizard.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/editingDomain/VirSatSaveJob.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/editingDomain/VirSatTransactionalEditingDomain.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/editingDomain/VirSatWorkspaceCommandStack.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/resources/VirSatResourceSet.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/structure/VirSatProjectResourceChangeListener.java
  de.dlr.sc.virsat.swtbot.test/pom.xml
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ASwtBotTestCase.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/util/VirSatWaitForProjectBuilder.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uieingine/ui/Activator.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/GenericEditor.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/excel/ExcelExportWizard.java
  launchers/SwtBot Tests.launch
Labels: build, quality

#422 Changed names in plugin.xml - (Task #421)
  de.dlr.sc.virsat.model.extension.funcelectrical/plugin.xml
  de.dlr.sc.virsat.model.extension.statemachines/plugin.xml
Labels: bug

#420 Improve Tree Traverser for use in CEFX
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/structural/level/HasLevelTreeTraverserMatcher.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/structural/tree/BeanStructuralTreeTraverser.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/structural/tree/IBeanStructuralTreeTraverserMatcher.java
  de.dlr.sc.virsat.model.extension.mechanical/src/de/dlr/sc/virsat/model/extension/mechanical/cad/CadExporter.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/concept/types/structural/tree/BeanStructuralTreeTraverserTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/concept/types/structural/tree/MockMatcher.java
Labels: feature

#431 Updated address of jacoco jar files - (Task #430)
  build.xml
Labels: build

#426 HOTIFX: Feature/release 4.9.3
  de.dlr.sc.virsat.docs.feature/docs/VirSat_Core_ReleaseNotes.txt
  de.dlr.sc.virsat.model.calculation.test/src/de/dlr/sc/virsat/model/calculation/compute/IncrementalEquationBuilderTest.java
  de.dlr.sc.virsat.model.calculation/src/de/dlr/sc/virsat/model/calculation/compute/IncrementalEquationBuilder.java
  de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/dvlm/concepts/registry/ActiveConceptConfigurationElementTest.java
  de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/dvlm/concepts/util/ActiveConceptHelperTest.java
  de.dlr.sc.virsat.model/src/de/dlr/sc/virsat/model/dvlm/concepts/util/ActiveConceptHelper.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/resources/VirSatResourceSetTest.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/resources/VirSatResourceSet.java
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/action/svn/SVNCommitAction.java
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/action/svn/SVNUpdateAction.java
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/util/svn/VirSatSvnRevisionStatusUtil.java
Labels: bug, quality, release

#435 Feature/task 434 correct codacy issues
  de.dlr.sc.virsat.build.test/src/de/dlr/sc/virsat/build/marker/util/VirSatInheritanceMarkerHelperTest.java
  de.dlr.sc.virsat.build.test/src/de/dlr/sc/virsat/build/marker/util/VirSatValidationMarkerHelperTest.java
  de.dlr.sc.virsat.model.calculation.test/src/de/dlr/sc/virsat/model/calculation/marker/VirSatEquationMarkerHelperTest.java
  de.dlr.sc.virsat.model.concept.test/src/de/dlr/sc/virsat/model/concept/generator/ConceptOutputConfigurationProviderTest.java
  de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/concept/migrator/ConceptMigrationHelperTest.java
  de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/dvlm/provider/DVLMRepositoryItemProviderTest.java
  de.dlr.sc.virsat.model.extension.funcelectrical.test/src/de/dlr/sc/virsat/model/extension/funcelectrical/marker/VirSatFuncelectricalMarkerHelperTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/build/validator/core/RepoValidatorsInstantiatorTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/model/TestCategoryCompositionTest.java
  de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/dvlm/util/DVLMUnresolvedReferenceExceptionTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/markers/VirSatProblemMarkerHelperTest.java
Labels: quality

#436 Included SVN Connector into target and product - (Task #203)
  de.dlr.sc.virsat.product/virsat_core.product
  de.dlr.sc.virsat.target/tmodel-src/virsat.tmodel
  de.dlr.sc.virsat.target/virsat.target
  launchers/VirSat Core Application (SuperUser).launch
  launchers/VirSat Core Application (other).launch
  launchers/VirSat Core Application (user).launch
Labels: build

#427 DND Override functionality for navigator
  de.dlr.sc.virsat.model.calculation.ui/plugin.xml
  de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/dvlm/util/DVLMCommandParameterApplicableForCheckTest.java
  de.dlr.sc.virsat.model.edit/src-gen/de/dlr/sc/virsat/model/dvlm/structural/provider/StructuralElementInstanceItemProvider.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/dvlm/util/DVLMCommandParameterApplicableForCheck.java
  de.dlr.sc.virsat.model.extension.ps.test/src/de/dlr/sc/virsat/model/extension/ps/dnd/ProductStructureDragAndDropInheritanceCommandHelperTest.java
  de.dlr.sc.virsat.model.extension.ps.test/src/de/dlr/sc/virsat/model/extension/ps/test/AllTests.java
  de.dlr.sc.virsat.model.extension.ps.test/src/de/dlr/sc/virsat/model/extension/ps/util/test/ProductStructureHelperTest.java
  de.dlr.sc.virsat.model.extension.ps.ui/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.ps.ui/plugin.xml
  de.dlr.sc.virsat.model.extension.ps.ui/src/.empty_src
  de.dlr.sc.virsat.model.extension.ps.ui/src/de/dlr/sc/virsat/model/extension/ps/ui/dropAdapter/ProductStructureInheritanceDropAdapterAssistant.java
  de.dlr.sc.virsat.model.extension.ps/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.extension.ps/src/de/dlr/sc/virsat/model/extension/ps/dnd/ProductStructureDragAndDropInheritanceCommandHelper.java
  de.dlr.sc.virsat.project.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/editingDomain/VirSatTransactionalEditingDomainTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/editingDomain/VirSatWorkspaceCommandStackTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/editingDomain/commands/VirSatClipboardCommandHelperTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/editingDomain/commands/VirSatCopyToClipboardCommandTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/editingDomain/commands/VirSatCutToClipboardCommandTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/editingDomain/commands/VirSatEditingDomainClipBoardTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/editingDomain/commands/VirSatPasteFromClipboardCommandTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/editingDomain/commands/dnd/VirSatDragAndDropInheritanceCommandHelperTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/resources/VirSatResourceSetTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/resources/command/AssignDisciplineCommandTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/resources/command/CreateSeiResourceAndFileCommandTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/structure/VirSatProjectBuilderTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/structure/VirSatProjectCommonsTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/structure/command/CreateAddSeiWithFileStructureCommandTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/structure/nature/VirSatProjectNatureTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/test/AProjectTestCase.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/test/AllTests.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/testAPI/VirsatTestAPI.java
  de.dlr.sc.virsat.project.ui/plugin.xml
  de.dlr.sc.virsat.project.ui/schema/de.dlr.sc.virsat.project.ui.navigator.exsd
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/dropAssist/ADVLMDropAdapaterAssistant.java
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/dropAssist/DVLMDefaultCopyAndPasteDropAdapterAssistant.java
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/dropAssist/DVLMDefaultInheritanceDropAdapterAssistant.java
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/dropAssist/DVLMDelegateDropAdapterAssistant.java
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/dropAssist/DVLMObjectDropAdapterAssistant.java
  de.dlr.sc.virsat.project/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/editingDomain/commands/VirSatEditingDomainClipBoard.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/editingDomain/commands/dnd/VirSatDragAndDropInheritanceCommandHelper.java
  de.dlr.sc.virsat.swtbot.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ASwtBotTestCase.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/CutCopyDeleteUndoTest.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/InheritanceTest.java
Labels: feature, quality

#440 Minor adjustment of release issue template (Task #439)
  .github/ISSUE_TEMPLATE/release.md
Labels: release

#444 Updated Mouse Scroll Mechanism
  checkStylesDefinition.xml
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/GenericEditor.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/AUiSnippetGenericTable.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/swt/forms/VirSatFormToolKit.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/swt/forms/VirSatMouseWheelScrollRedirectListener.java
Labels: feature, quality, ui

#443 minor typo fix
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ASwtBotTestCase.java
  known_authors.txt
Labels: quality

#446 Excluding generated Code from PullRequests
  .gitattributes
Labels: build

#448 Export virsat.swtbot.test package - (Task #447)
  de.dlr.sc.virsat.swtbot.test/META-INF/MANIFEST.MF
Labels: build, quality
