Repository virtualsatellite/VirtualSatellite4-Core, pull requests merged in 2020-06, with the labels that each got.

#618 Remove obsolete method in inheritance copier
  de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/dvlm/inheritance/InheritanceCopierTest.java
  de.dlr.sc.virsat.model/src/de/dlr/sc/virsat/model/dvlm/inheritance/InheritanceCopier.java
Labels: quality

#594 Added BeanUnitProperty Factory - (Task #286)
  de.dlr.sc.virsat.graphiti.test/src/de/dlr/sc/virsat/graphiti/diagram/BeanIndependenceSolverTest.java
  de.dlr.sc.virsat.graphiti/src/de/dlr/sc/virsat/graphiti/diagram/BeanIndependenceSolver.java
  de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyFactoryTest.java
  de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/edit/test/AllTests.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/factory/BeanPropertyFactory.java
Labels: feature, quality

#619 Sortable columns in QUDV Editor
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/commonSorter/LabelColumnSorter.java
  de.dlr.sc.virsat.qudv.ui/src/de/dlr/sc/virsat/qudv/ui/editor/snippets/UiSnippetQuantityKindManagement.java
  de.dlr.sc.virsat.qudv.ui/src/de/dlr/sc/virsat/qudv/ui/editor/snippets/UiSnippetUnitManagement.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/AUiSnippetEStructuralFeatureTable.java
Labels: comfort/usability, ui

#620 convertFromSourceToTarget now throws IllegalArgumentException for mismatching QKs
  de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/dvlm/qudv/util/QudvUnitHelperTest.java
  de.dlr.sc.virsat.model/src/de/dlr/sc/virsat/model/dvlm/qudv/util/QudvUnitHelper.java
Labels: bug

#630 Replaced force delete with quiet delete - (Task #629)
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/dataaccess/VirSatGitAccessTest.java
Labels: build

#631 Added BeanPropertyReference
  de.dlr.sc.virsat.model.concept.test/resources/expectedOutputFilesForGenerators/ACategoryBeanTypesAndReferences.java
  de.dlr.sc.virsat.model.concept/src/de/dlr/sc/virsat/model/concept/generator/beans/GenerateCategoryBeans.xtend
  de.dlr.sc.virsat.model.concept/xtend-gen/de/dlr/sc/virsat/model/concept/generator/beans/GenerateCategoryBeans.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyReference.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyReferenceTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/test/AllTests.java
Labels: quality

#617 Updated External Lib Apache Commons-Cli build process
  de.dlr.sc.virsat.external.lib.commons.cli/.classpath
  de.dlr.sc.virsat.external.lib.commons.cli/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.external.lib.commons.cli/about.html
  de.dlr.sc.virsat.external.lib.commons.cli/about_files/LICENSE.txt
  de.dlr.sc.virsat.external.lib.commons.cli/about_files/NOTICE.txt
  de.dlr.sc.virsat.external.lib.commons.cli/about_files/THIRD-PARTY.txt
  de.dlr.sc.virsat.external.lib.commons.cli/build.properties
  de.dlr.sc.virsat.external.lib.commons.cli/externalLib/commons-cli-1.3.1/.gitignore
  de.dlr.sc.virsat.external.lib.commons.cli/externalLib/commons-cli-1.3.1/CONTRIBUTING.md
  de.dlr.sc.virsat.external.lib.commons.cli/externalLib/commons-cli-1.3.1/LICENSE.txt
  de.dlr.sc.virsat.external.lib.commons.cli/externalLib/commons-cli-1.3.1/NOTICE.txt
  de.dlr.sc.virsat.external.lib.commons.cli/externalLib/commons-cli-1.3.1/README.md
  de.dlr.sc.virsat.external.lib.commons.cli/externalLib/commons-cli-1.3.1/RELEASE-NOTES.txt
  de.dlr.sc.virsat.external.lib.commons.cli/externalLib/commons-cli-1.3.1/commons-cli-1.3.1-javadoc.jar
  de.dlr.sc.virsat.external.lib.commons.cli/externalLib/commons-cli-1.3.1/docs/.empty
  de.dlr.sc.virsat.external.lib.commons.cli/externalLib/maven/commons-cli.jar
  de.dlr.sc.virsat.external.lib.commons.cli/pom.xml
Labels: build

#634 Improved stability of test cases.
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/editingDomain/VirSatTransactionalEditingDomainTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/structure/VirSatProjectCommonsTest.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/editingDomain/VirSatTransactionalEditingDomain.java
Labels: build, quality

#622 Updated External Lib Apache Commons Math build process
  de.dlr.sc.virsat.external.lib.commons.math/.classpath
  de.dlr.sc.virsat.external.lib.commons.math/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.external.lib.commons.math/about.html
  de.dlr.sc.virsat.external.lib.commons.math/about_files/THIRD-PARTY.txt
  de.dlr.sc.virsat.external.lib.commons.math/build.properties
  de.dlr.sc.virsat.external.lib.commons.math/externalLib/commons-math3-3.6/.gitignore
  de.dlr.sc.virsat.external.lib.commons.math/externalLib/commons-math3-3.6/RELEASE-NOTES.txt
  de.dlr.sc.virsat.external.lib.commons.math/externalLib/commons-math3-3.6/commons-math3-3.6.jar
  de.dlr.sc.virsat.external.lib.commons.math/externalLib/maven/commons-math3.jar
  de.dlr.sc.virsat.external.lib.commons.math/pom.xml
Labels: build

#644 Added test cases for validation
  de.dlr.sc.virsat.build.ui/src/de/dlr/sc/virsat/build/marker/ui/MarkerImageProvider.java
  de.dlr.sc.virsat.build/src/de/dlr/sc/virsat/build/validator/core/DvlmNamingConventionValidator.java
  de.dlr.sc.virsat.project.ui/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/perspective/CorePerspective.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ASwtBotTestCase.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ProjectUiAllTests.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ValidatorTest.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/util/SwtBotHyperlink.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/general/UiSnippetIName.java
Labels: quality

#648 SwtBot Test Cases for StateMachine diagrams
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/stateMachines/StateMachineResizeFeature.java
  de.dlr.sc.virsat.swtbot.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ProjectUiAllTests.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/StateMachineDiagramTest.java
  launchers/SwtBot Tests.launch
Labels: quality, ui

#653 Added swtbot test for creating CA in inheritance hierarchy - (Task #640)
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ASwtBotTestCase.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/InheritanceTest.java
Labels: quality

#659 Extended test case for collapsing sections - (Task #654)
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/EditorTest.java
Labels: quality

#650 Added QUDV Wizard UI test cases - (Task #647)
  de.dlr.sc.virsat.qudv.ui/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.qudv.ui/src/de/dlr/sc/virsat/qudv/ui/editor/snippets/UiSnippetQuantityKindManagement.java
  de.dlr.sc.virsat.qudv.ui/src/de/dlr/sc/virsat/qudv/ui/editor/snippets/UiSnippetUnitManagement.java
  de.dlr.sc.virsat.qudv.ui/src/de/dlr/sc/virsat/qudv/ui/wizards/QudvQuantityKindSetupWizard.java
  de.dlr.sc.virsat.qudv.ui/src/de/dlr/sc/virsat/qudv/ui/wizards/SimpleQuantityKindWizard.java
  de.dlr.sc.virsat.qudv.ui/src/de/dlr/sc/virsat/qudv/ui/wizards/pages/AQuantityKindWizardPage.java
  de.dlr.sc.virsat.qudv.ui/src/de/dlr/sc/virsat/qudv/ui/wizards/pages/AUnitWizardPage.java
  de.dlr.sc.virsat.qudv.ui/src/de/dlr/sc/virsat/qudv/ui/wizards/pages/QudvQuantityKindSetupWizardSelectionPage.java
  de.dlr.sc.virsat.qudv.ui/src/de/dlr/sc/virsat/qudv/ui/wizards/pages/SimpleQuantityKindWizardPageOne.java
  de.dlr.sc.virsat.qudv.ui/src/de/dlr/sc/virsat/qudv/ui/wizards/pages/SimpleUnitWizardPageOne.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ASwtBotTestCase.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ProductStructureTest.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/ProjectUiAllTests.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/QudvWizardTest.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/AUiSnippetEStructuralFeatureTable.java
Labels: quality

#646 Fixed method calls in Editing domain - (Task #645)
  de.dlr.sc.virsat.graphiti.ui/src/de/dlr/sc/virsat/graphiti/ui/diagram/editor/VirSatDiagramPersistencyBehavior.java
  de.dlr.sc.virsat.model.calculation.ui/src/de/dlr/sc/virsat/model/calculation/ui/editor/EquationSectionUriEditorInput.java
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/migrator/handler/MigrateConceptToLatestHandler.java
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/saveablesprovider/VirSatResourceSetSaveable.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/editingDomain/VirSatTransactionalEditingDomain.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/general/UiSnippetActiveConcepts.java
Labels: bug

#668 Added milliseconds to units creation script - (Task #486)
  de.dlr.sc.virsat.model/src/de/dlr/sc/virsat/model/dvlm/qudv/util/QudvUnitHelper.java
Labels: comfort/usability

#636 Changed handling of nested categories in set functions - (Task #635)
  de.dlr.sc.virsat.model.calculation.test/src/de/dlr/sc/virsat/model/calculation/compute/ExpressionHelperTest.java
  de.dlr.sc.virsat.model.calculation/src/de/dlr/sc/virsat/model/calculation/compute/ExpressionHelper.java
Labels: bug

#638 Implementing ComposedPropertyBean
  de.dlr.sc.virsat.model.concept.test/resources/expectedOutputFilesForGenerators/ACategoryBeanTypesAndReferences.java
  de.dlr.sc.virsat.model.concept/src/de/dlr/sc/virsat/model/concept/generator/beans/GenerateCategoryBeans.xtend
  de.dlr.sc.virsat.model.concept/xtend-gen/de/dlr/sc/virsat/model/concept/generator/beans/GenerateCategoryBeans.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyComposed.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/concept/types/property/BeanPropertyComposedTest.java
Labels: quality

#661 Remvoing duplicate messages when removing referenced objects
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/dvlm/command/CreateDeleteWithReferencingCategoryAssignmentsCommand.java
  de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/ecore/VirSatEcoreUtilTest.java
  de.dlr.sc.virsat.model/src/de/dlr/sc/virsat/model/ecore/VirSatEcoreUtil.java
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/handler/DeleteCategoryAssignmentHandler.java
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/handler/DeleteStructuralElementInstanceHandler.java
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/structure/dialog/ReferencedDeleteDialog.java
Labels: bug, ui

#662 Added SwtBot test for deleting referenced objects - (Task #655)
  de.dlr.sc.virsat.project.ui/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/CutCopyDeleteUndoTest.java
Labels: quality

#637 Fixing Resource Access Builder to create correct java code
  de.dlr.sc.virsat.model.concept.test/resources/PluginXml.java
  de.dlr.sc.virsat.model.concept.test/resources/expectedOutputFilesForResourceAccessBuilder/MANIFEST.MF
  de.dlr.sc.virsat.model.concept.test/resources/expectedOutputFilesForResourceAccessBuilder/ManifestMF.java
  de.dlr.sc.virsat.model.concept.test/resources/expectedOutputFilesForResourceAccessBuilder/PluginUiXml.java
  de.dlr.sc.virsat.model.concept.test/resources/expectedOutputFilesForResourceAccessBuilder/PluginXml.java
  de.dlr.sc.virsat.model.concept.test/resources/expectedOutputFilesForResourceAccessBuilder/plugin.xml
  de.dlr.sc.virsat.model.concept.test/resources/expectedOutputFilesForResourceAccessBuilder/pluginUi.xml
  de.dlr.sc.virsat.model.concept.test/resources/plugin.xml
  de.dlr.sc.virsat.model.concept.test/src/de/dlr/sc/virsat/model/concept/builder/resources/ResourceAccessBuilderTest.java
  de.dlr.sc.virsat.model.concept.test/src/de/dlr/sc/virsat/model/concept/test/TestActivator.java
  de.dlr.sc.virsat.model.concept/src/de/dlr/sc/virsat/model/concept/builder/resources/ResourceAccessBuilder.xtend
  de.dlr.sc.virsat.model.concept/xtend-gen/de/dlr/sc/virsat/model/concept/builder/resources/ResourceAccessBuilder.java
Labels: bug, build

#628 Updated External Lib Json-Simple build process
  de.dlr.sc.virsat.external.lib.matlabfile/.classpath
  de.dlr.sc.virsat.external.lib.matlabfile/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.external.lib.matlabfile/about.html
  de.dlr.sc.virsat.external.lib.matlabfile/about_files/THIRD-PARTY.txt
  de.dlr.sc.virsat.external.lib.matlabfile/build.properties
  de.dlr.sc.virsat.external.lib.matlabfile/externalLib/maven/mfl-core.jar
  de.dlr.sc.virsat.external.lib.matlabfile/externalLib/mfl-core-0.5.6-javadoc.jar
  de.dlr.sc.virsat.external.lib.matlabfile/externalLib/mfl-core-0.5.6-sources.jar
  de.dlr.sc.virsat.external.lib.matlabfile/pom.xml
  de.dlr.sc.virsat.external.lib/maven/pom.xml
Labels: build

#669 Upgrading to Eclipse 2020-06
  de.dlr.sc.virsat.apps.test/src/de/dlr/sc/virsat/apps/initializer/ManifestRequiredBundlesConceptUpdaterTest.java
  de.dlr.sc.virsat.model.calculation.ide/src-gen/de/dlr/sc/virsat/model/calculation/ide/contentassist/antlr/PartialEquationDSLContentAssistParser.java
  de.dlr.sc.virsat.model.calculation.ui/plugin.xml_gen
  de.dlr.sc.virsat.model.calculation/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.calculation/src-gen/de/dlr/sc/virsat/model/calculation/services/EquationDSLGrammarAccess.java
  de.dlr.sc.virsat.model.concept.ide/src-gen/de/dlr/sc/virsat/model/concept/ide/contentassist/antlr/PartialConceptLanguageContentAssistParser.java
  de.dlr.sc.virsat.model.concept.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.concept.ui/plugin.xml_gen
  de.dlr.sc.virsat.model.concept/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.concept/src-gen/de/dlr/sc/virsat/model/concept/parser/antlr/internal/InternalConceptLanguage.g
  de.dlr.sc.virsat.model.concept/src-gen/de/dlr/sc/virsat/model/concept/parser/antlr/internal/InternalConceptLanguageParser.java
  de.dlr.sc.virsat.model.concept/src-gen/de/dlr/sc/virsat/model/concept/services/ConceptLanguageGrammarAccess.java
  de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/concept/migrator/AMigratorTest.java
  de.dlr.sc.virsat.model.edit.test/src/de/dlr/sc/virsat/model/dvlm/concepts/registry/ActiveConceptConfigurationElementTest.java
  de.dlr.sc.virsat.model.edit/src/de/dlr/sc/virsat/model/concept/migrator/AMigrator.java
  de.dlr.sc.virsat.model.extension.funcelectrical/src/de/dlr/sc/virsat/model/extension/funcelectrical/html/ExportHelper.java
  de.dlr.sc.virsat.model.extension.mechanical.test/src/de/dlr/sc/virsat/model/extension/mechanical/cad/CadImporterTest.java
  de.dlr.sc.virsat.model.extension.ps.test/src/de/dlr/sc/virsat/model/extension/ps/dnd/ProductStructureDragAndDropInheritanceCommandHelperTest.java
  de.dlr.sc.virsat.model.extension.tests.edit.test/src/de/dlr/sc/virsat/model/extension/tests/edit/test/AllTests.java
  de.dlr.sc.virsat.model.extension.tests.edit.test/src/de/dlr/sc/virsat/project/resources/dmf/DmfResourceTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/concept/list/ArrayInstanceListIteratorTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/concept/types/structural/tree/BeanStructuralTreeTraverserTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/concept/types/util/BeanCategoryAssignmentHelperTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/concept/types/util/BeanStructuralElementInstanceHelperTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/dvlm/mat/MatExporterTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/model/TestCategoryCompositionArrayStaticTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/model/TestCategoryIntrinsicArrayStaticTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/model/TestCategoryReferenceCategoryArrayStaticTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/model/TestCategoryReferencePropertyArrayStaticTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/test/AllTests.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/project/resources/dmf/DmfResourceTest.java
  de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/dvlm/categories/CategoryTest.java
  de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/dvlm/categories/propertydefinitions/EnumPropertyHelperTest.java
  de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/dvlm/categories/util/CategoryInstantiatorTest.java
  de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/dvlm/concepts/ConceptTest.java
  de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/dvlm/inheritance/InheritanceCopierTest.java
  de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/dvlm/tree/TreeTraverserTest.java
  de.dlr.sc.virsat.model.test/src/de/dlr/sc/virsat/model/dvlm/util/DVLMCopierTest.java
  de.dlr.sc.virsat.product/virsat_core.product
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/editingDomain/commands/dnd/VirSatDragAndDropInheritanceCommandHelperTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/resources/VirSatResourceSetTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/structure/VirSatProjectBuilderTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/structure/VirSatProjectCommonsTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/structure/command/CreateAddSeiWithFileStructureCommandTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/structure/command/CreateRemoveSeiWithFileStructureCommandTest.java
  de.dlr.sc.virsat.project.test/src/de/dlr/sc/virsat/project/structure/operation/NoUndoDeleteResourceOperationTest.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/resources/dmf/DmfResourceSaveCommand.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/dataaccess/VirSatGitAccessTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/repository/ServerRepositoryTest.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/CutCopyDeleteUndoTest.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/InheritanceTest.java
  de.dlr.sc.virsat.target/tmodel-src/virsat.tmodel
  de.dlr.sc.virsat.target/virsat.target
Labels: build
