Repository virtualsatellite/VirtualSatellite4-Core, pull requests merged in 2022-06, with the labels that each got.

#1096 Deploy jakarta.activation - Task #1062
  de.dlr.sc.virsat.model.feature/feature.xml
Labels: bug

#1100 Fixed warnings produced in newest IDE version - Task #1099
  de.dlr.sc.virsat.external.lib.apache.poi/build.properties
  de.dlr.sc.virsat.external.lib.commons.csv/build.properties
  de.dlr.sc.virsat.external.lib.swagger/build.properties
  de.dlr.sc.virsat.model.concept/src/de/dlr/sc/virsat/model/concept/project/IProjectBuilderInfo.java
Labels: quality

#1089 Changed VirSatNavigatorSeiSorter to return zero - Task #1088
  .mailmap
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/commonSorter/VirSatNavigatorSeiSorter.java
  de.dlr.sc.virsat.project.ui/src/de/dlr/sc/virsat/project/ui/navigator/contentProvider/VirSatProjectContentProvider.java
Labels: quality

#1103 Extension of State Machines to support simple nesting
  de.dlr.sc.virsat.graphiti.ui/src/de/dlr/sc/virsat/graphiti/ui/handler/AOpenInDiagramEdiorHandler.java
  de.dlr.sc.virsat.model.extension.statemachines.test/src-gen/de/dlr/sc/virsat/model/extension/statemachines/migrator/AMigrator1v6Test.java
  de.dlr.sc.virsat.model.extension.statemachines.test/src-gen/de/dlr/sc/virsat/model/extension/statemachines/test/AllTestsGen.java
  de.dlr.sc.virsat.model.extension.statemachines.test/src/de/dlr/sc/virsat/model/extension/statemachines/migrator/Migrator1v6Test.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/plugin.xml
  de.dlr.sc.virsat.model.extension.statemachines.ui/src-gen/de/dlr/sc/virsat/model/extension/statemachines/ui/snippet/AUiSnippetTableStateConstraintsAllowsConstraint.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src-gen/de/dlr/sc/virsat/model/extension/statemachines/ui/snippet/AUiSnippetTableStateConstraintsForbidsConstraint.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src-gen/de/dlr/sc/virsat/model/extension/statemachines/ui/snippet/AUiSnippetTableStateStatesState.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src-gen/de/dlr/sc/virsat/model/extension/statemachines/ui/snippet/AUiSnippetTableStateTransitionsTransition.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src-gen/de/dlr/sc/virsat/model/extension/statemachines/ui/snippet/AUiSnippetTableStateTriggerEventsTransitionTriggerEvent.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/propertyTester/OpenStateMachineTester.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/StateMachineDiagramFeatureProvider.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/abstractConnection/AbstractConnectionAddFeature.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/abstractConnection/AbstractConnectionCreateFeature.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/stateMachines/StateMachineUpdateFeature.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/states/StateAddFeature.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/states/StateLayoutFeature.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/states/StateSetAsInitialStateFeature.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/states/StateUnsetAsInitialStateFeature.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/transitions/TransitionCreateFeature.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/diagram/features/transitions/TransitionLabelProvider.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/snippet/UiSnippetTableStateConstraintsAllowsConstraint.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/snippet/UiSnippetTableStateConstraintsForbidsConstraint.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/snippet/UiSnippetTableStateStatesState.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/snippet/UiSnippetTableStateTransitionsTransition.java
  de.dlr.sc.virsat.model.extension.statemachines.ui/src/de/dlr/sc/virsat/model/extension/statemachines/ui/snippet/UiSnippetTableStateTriggerEventsTransitionTriggerEvent.java
  de.dlr.sc.virsat.model.extension.statemachines/concept/concept.concept
  de.dlr.sc.virsat.model.extension.statemachines/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.statemachines/concept/concept_v1_6.xmi
  de.dlr.sc.virsat.model.extension.statemachines/plugin.xml
  de.dlr.sc.virsat.model.extension.statemachines/src-gen/de/dlr/sc/virsat/model/extension/statemachines/migrator/AMigrator1v6.java
  de.dlr.sc.virsat.model.extension.statemachines/src-gen/de/dlr/sc/virsat/model/extension/statemachines/model/AState.java
  de.dlr.sc.virsat.model.extension.statemachines/src/de/dlr/sc/virsat/model/extension/statemachines/migrator/Migrator1v6.java
Labels: feature

#1106 Also removes native_lib from blundle classpath for zmq
  de.dlr.sc.virsat.external.lib.zmq.linux.x86_64/META-INF/MANIFEST.MF
Labels: build

#1068 Migration to Eclipse 2022-03
  de.dlr.sc.virsat.dependencies.feature/feature.xml
  de.dlr.sc.virsat.external.lib.feature/feature.xml
  de.dlr.sc.virsat.external.lib.jersey/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.external.lib.jersey/src/de/dlr/virsat/external/lib/jersey/servlet/ApplicationServletContainer.java
  de.dlr.sc.virsat.external.lib.swagger/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.calculation/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.concept.test/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.concept/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.model.ext.core/concept/concept.genmodel
  de.dlr.sc.virsat.model.extension.funcelectrical.test/src/de/dlr/sc/virsat/model/extension/funcelectrical/excel/exporter/FuncElecExporterTest.java
  de.dlr.sc.virsat.model.extension.funcelectrical.test/src/de/dlr/sc/virsat/model/extension/funcelectrical/excel/importer/FuncElecImporterTest.java
  de.dlr.sc.virsat.model.extension.funcelectrical.test/src/de/dlr/sc/virsat/model/extension/funcelectrical/excel/importer/ImportValidatorTest.java
  de.dlr.sc.virsat.model.extension.funcelectrical.test/src/de/dlr/sc/virsat/model/extension/funcelectrical/test/AExcelTestCase.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/apps/api/external/ModelAPIWithTestConceptTest.java
  de.dlr.sc.virsat.model.extension.tests.test/src/de/dlr/sc/virsat/model/extension/tests/test/AllTests.java
  de.dlr.sc.virsat.model.extension.tests/concept/concept.genmodel
  de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/VtkClientView.java
  de.dlr.sc.virsat.model.feature/feature.xml
  de.dlr.sc.virsat.product/virsat_core.product
  de.dlr.sc.virsat.product/virsat_server.product
  de.dlr.sc.virsat.server.feature/feature.xml
  de.dlr.sc.virsat.server.test/resources/https.properties
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/configuration/ServerConfigurationTest.java
  de.dlr.sc.virsat.server.test/src/de/dlr/sc/virsat/server/jetty/VirSatJettyServerTest.java
  de.dlr.sc.virsat.server/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.server/resources/server.properties
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/classloader/BundleDependencyClassLoader.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/configuration/ServerConfiguration.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/jetty/VirSatJettyServer.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/servlet/RepoManagementServlet.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/servlet/VirSatModelAccessServlet.java
  de.dlr.sc.virsat.target/tmodel-src/virsat.tmodel
  de.dlr.sc.virsat.target/tmodel-src/virsat_windows.tmodel
  de.dlr.sc.virsat.target/virsat_linux.target
  de.dlr.sc.virsat.target/virsat_windows.target
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/handler/git/GitCommitHandler.java
  de.dlr.sc.virsat.team.ui/src/de/dlr/sc/virsat/team/ui/handler/git/GitUpdateHandler.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/dialog/ActiveConceptSelectionDialogFactory.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/general/UiSnippetSuppressedValidators.java
  maven/pom.xml
Labels: feature
