Repository virtualsatellite/VirtualSatellite4-Core, pull requests merged in 2024-11, with the labels that each got.

#1222 Fioxing issue with decoding url in diagram editor
  de.dlr.sc.virsat.graphiti.ui/src/de/dlr/sc/virsat/graphiti/ui/diagram/editor/VirSatDiagramUpdateBehavior.java
  de.dlr.sc.virsat.graphiti/META-INF/MANIFEST.MF
  de.dlr.sc.virsat.graphiti/src/de/dlr/sc/virsat/graphiti/util/DiagramHelper.java
Labels: bug

#1233 Fixed issue with not closing editor
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/editingDomain/VirSatTransactionalEditingDomain.java
  de.dlr.sc.virsat.project/src/de/dlr/sc/virsat/project/resources/VirSatResourceSet.java
  de.dlr.sc.virsat.swtbot.test/src/de/dlr/sc/virsat/swtbot/test/EditorTest.java
  de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/GenericEditor.java
Labels: bug, quality

#1221 Added capability to scale STL geometries in the visualization
  de.dlr.sc.virsat.model.extension.visualisation.test/src-gen/de/dlr/sc/virsat/model/extension/visualisation/migrator/AMigrator1v5Test.java
  de.dlr.sc.virsat.model.extension.visualisation.test/src-gen/de/dlr/sc/virsat/model/extension/visualisation/test/AllTestsGen.java
  de.dlr.sc.virsat.model.extension.visualisation.test/src-gen/de/dlr/sc/virsat/model/extension/visualisation/validator/AVisualisationValidatorTest.java
  de.dlr.sc.virsat.model.extension.visualisation.test/src/de/dlr/sc/virsat/model/extension/visualisation/VisualisationTreeManagerTest.java
  de.dlr.sc.virsat.model.extension.visualisation.test/src/de/dlr/sc/virsat/model/extension/visualisation/migrator/Migrator1v5Test.java
  de.dlr.sc.virsat.model.extension.visualisation.ui/plugin.xml
  de.dlr.sc.virsat.model.extension.visualisation.ui/src-gen/de/dlr/sc/virsat/model/extension/visualisation/propertyTester/AConceptEnabledTester.java
  de.dlr.sc.virsat.model.extension.visualisation.ui/src/de/dlr/sc/virsat/model/extension/visualisation/ui/vtkClient/VtkTreeManager.java
  de.dlr.sc.virsat.model.extension.visualisation/concept/concept.concept
  de.dlr.sc.virsat.model.extension.visualisation/concept/concept.xmi
  de.dlr.sc.virsat.model.extension.visualisation/concept/concept_v1_5.xmi
  de.dlr.sc.virsat.model.extension.visualisation/localLib/visProtocol.jar
  de.dlr.sc.virsat.model.extension.visualisation/plugin.xml
  de.dlr.sc.virsat.model.extension.visualisation/proto/visProto.proto
  de.dlr.sc.virsat.model.extension.visualisation/src-gen/de/dlr/sc/virsat/model/extension/visualisation/migrator/AMigrator1v5.java
  de.dlr.sc.virsat.model.extension.visualisation/src-gen/de/dlr/sc/virsat/model/extension/visualisation/model/AVisualisation.java
  de.dlr.sc.virsat.model.extension.visualisation/src-gen/de/dlr/sc/virsat/model/extension/visualisation/validator/AVisualisationValidator.java
  de.dlr.sc.virsat.model.extension.visualisation/src/de/dlr/sc/virsat/model/extension/visualisation/comparison/CompareModelGeometry.java
  de.dlr.sc.virsat.model.extension.visualisation/src/de/dlr/sc/virsat/model/extension/visualisation/migrator/Migrator1v5.java
  de.dlr.sc.virsat.model.extension.visualisation/src/de/dlr/sc/virsat/model/extension/visualisation/model/Visualisation.java
  de.dlr.sc.virsat.model.extension.visualisation/src/de/dlr/sc/virsat/model/extension/visualisation/shape/Shape.java
  de.dlr.sc.virsat.model.extension.visualisation/src/de/dlr/sc/virsat/model/extension/visualisation/treemanager/TreeManager.java
Labels: feature

#1237 Feature/1196 post request fix name param
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/VirSatServerApplication.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/model/StructuralElementInstanceResource.java
  de.dlr.sc.virsat.server/src/de/dlr/sc/virsat/server/resources/modelaccess/ModelAccessResource.java
Labels: Server
